### ISSUE TITLE
Why not GPLv3+?

### ISSUE THREAD

**Issue by nikitasius** [maidsafe/routing#1119]
Hi!
Why you don't use GPLv3:
https://github.com/maidsafe/routing/blob/master/LICENSE

**Comment by NickLambert** [comment]
Hi @nikitasius, 

We do: https://github.com/maidsafe/routing/blob/master/COPYING. Each lib is dual sourced so that developers/companies can decide which best suits their use case. I hope this helps, let me know if you have any further questions.

**Comment by nikitasius** [comment]
Hi @NickLambert,

> Each lib is dual sourced so that developers/companies can decide which best suits their use case.
Great, thank you! It's great!
