### ISSUE TITLE
Cargo versions different to repo tags

### ISSUE THREAD

**Issue by iancoleman** [maidsafe/routing#1131]
I'm trying to checkout `routing 0.23.4` from the repo (safe_vault 0.11.0 depends on it)

There is no tag in the repo for this version.

[Cargo lists all versions of routing](https://crates.io/crates/routing/versions). 0.23.3 and 0.23.4 are listed in cargo but are not tagged in the repo.

I'm compiling safe_vault 0.11.0 from source with a customized local routing. But the lack of a tag means I don't know which commit of routing to use for 0.23.4

**Comment by frabrunelle** [comment]
Yeah there is no tag but you can see the source of 0.23.4 by looking at the 0.23 branch: https://github.com/maidsafe/routing/tree/0.23

**Comment by Viv-Rajkumar** [comment]
Cheers for letting us know @iancoleman 

[Tag 0.23.4](https://github.com/maidsafe/routing/tree/0.23.4) should be available now.
