### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by obv-mikhail** [maidsafe/routing#1132]
http://maidsafe.net/Whitepapers/pdf/MaidSafeDistributedHashTable.pdf

**Comment by davidpbrown** [comment]
Appears to be re: https://github.com/maidsafe/routing/blob/master/README.md
> This is particularly useful in a continually fluid network as described [here](http://maidsafe.net/Whitepapers/pdf/MaidSafeDistributedHashTable.pdf)

=> http://maidsafe.net/Whitepapers/pdf/MaidSafeDistributedHashTable.pdf
then likely should be
https://github.com/maidsafe/Whitepapers/blob/gh-pages/pdf/MaidSafeDistributedHashTable.pdf

more generally, I wonder
http://maidsafe.net/Whitepapers/pdf/*
should now be
https://github.com/maidsafe/Whitepapers/tree/gh-pages/pdf

**Comment by frabrunelle** [comment]
@davidpbrown The whitepapers were moved to `docs.maidsafe.net`.

So the URL would be http://docs.maidsafe.net/Whitepapers/pdf/MaidSafeDistributedHashTable.pdf.

**Comment by davidpbrown** [comment]
@frabrunelle thanks.. a pity there isn't an index/list apparent there too, similar to that suggeseted by https://github.com/maidsafe/Whitepapers/tree/gh-pages/pdf

**Comment by frabrunelle** [comment]
You can find a list of the whitepapers here: https://safenetwork.wiki/en/Whitepapers
