### ISSUE TITLE
Possible replay attack with a simple fix

### ISSUE THREAD

**Issue by Lindsey17** [maidsafe/routing#1644]
This issue is from a comment @Fraser999 made on Slack so it doesn't get forgotten about.

Fraser and @ustulation think that if a malicious elder caches a client's two messages (initial request and confirmation), then it can wait for the client to go offline, then connect to the section pretending to be that client and replay those.  However, if all new connections are required at the routing level to go through a challenge it should be ok here.  E.g. Routing gets notified of a new connection, sends a random string to peer and check it's able to sign the string before accepting any other traffic.

**Comment by madadam** [comment]
No longer relevant as routing doesn't deal with client. Transferred over to https://github.com/maidsafe/safe-vault/issues/989
