### ISSUE TITLE
Possible replay attack

### ISSUE THREAD

**Issue by Lindsey17** [maidsafe/routing#1645]
This issue is from a comment @Fraser999 made on Slack so it doesn't get forgotten about.

It needs to be ensured there's no way for a single (or two out of the three even) malicious elder to reswarm a client message to get the src section to revote on it.  If one src elder can replay/reswarm the original client request, and also the original client confirmation and get the src elders to revote, then it's fully replay-able.

**Comment by madadam** [comment]
No longer relevant as routing doesn't deal with client. Transferred over to https://github.com/maidsafe/safe-vault/issues/989
