### ISSUE TITLE
Swarm at destination

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/routing#1657]
=> Maybe the message can simply go through PARSEC (?)

**Comment by dirvine** [comment]
Swarm here will be simple send to all members directly.  For small groups, this is the most efficient and simplest to code up.  Also keeps us on side of guaranteed delivery for the price of approx `(n*3)` messages in last hop.

**Comment by octol** [comment]
Conveniently this (simple send) is already implemented so I will close this issue
