### ISSUE TITLE
Replace signature accumulation in Delivery Group with PARSEC consensus (Probably no longer wanted)

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/routing#1660]
!!! This may not be something we want to do as we may want to avoid using Parsec for `Get`.

=> Note: as the outcome of this, we won’t enforce correct behaviour from other nodes, but we do want for correct nodes to always behave correctly (i.e: only send a message with section authority when it is definitive that a quorum of the section wants to send this message)

Bart+JP: not necessarily as easy as we thought so not necessarily a good idea to do.
Was suppose to simplify code. Avoid timers.

**Comment by jeanphilippeD** [comment]
This is no longer wanted as we want to be able to do Secure Message Relay without using Parsec, For example for the Get Mutable data flow.

**Comment by jeanphilippeD** [comment]
Closed as per https://github.com/maidsafe/routing/issues/1660#issuecomment-525771143
