### ISSUE TITLE
Need to replace mpsc : : Sender in quic-p2p with something that supports select over at least 2 channels

### ISSUE THREAD

**Issue by Lindsey17** [maidsafe/routing#1680]
=> crossbeam-channel favoured as a solution

**Comment by madadam** [comment]
This is already done (and merged) in quic-p2p. Will be done in routing's mock quic-p2p in the next PR.

**Comment by Lindsey17** [comment]
Should I close this issue then @madadam ?

**Comment by madadam** [comment]
This is done as part of https://github.com/maidsafe/routing/pull/1692.

**Comment by madadam** [comment]
Closed in #1692
