### ISSUE TITLE
Connection logic is simpler in quic-p2p

### ISSUE THREAD

**Issue by Lindsey17** [maidsafe/routing#1683]
=> Some state can be removed from peer manager
=> More fleshing out needed

**Comment by madadam** [comment]
Here is what I think we can do:
1. Merge the `Connected` and `JoiningNode` states into one
2. Remove the `Candidate` state and all the candidate related logic. It should be moved to `Chain`.
3. Address the TODO in `peer_map.rs` about the edge cases
4. See if `PeerMap` can be simplified
5. Consider merging `PeerMap` and `PeerManager` into single type, if it makes sense

**Comment by madadam** [comment]
PR: https://github.com/maidsafe/routing/pull/1693
