### ISSUE TITLE
Adapt mock API to quic-p2p API when following change gets merged to quic-p2p

### ISSUE THREAD

**Issue by Lindsey17** [maidsafe/routing#1685]
=> [Return unsent message](https://github.com/maidsafe/quic-p2p/commit/5878d306ff3852d631ee287c95fc84e20bfa06c7)

**Comment by jeanphilippeD** [comment]
Mock quic_p2p is already doing the correct thing and always send back a UnsentUserMessage when a failure occurs (cc @madadam).

Raised https://github.com/maidsafe/quic-p2p/issues/64 in quic_p2p.
No more work is needed in routing crate.
