### ISSUE TITLE
Changes to ConnInfoReq/Resp messages

### ISSUE THREAD

**Issue by Lindsey17** [maidsafe/routing#1686]
=> Are these messages single authority <-> single authority anymore or do you just query ConnInfo from the set of elders/section a node is expected to belong to?

=> This was mentioned during the quic-p2p work where nodes were expected/provided with new member conn-info from the group authority itself rather than needing to query the concerned node directly as conn info is static without hole-punch

**Comment by dirvine** [comment]
These messages are just direct messages on the network. Node to node and sent via RMD

**Comment by jeanphilippeD** [comment]
Based on @dirvine comment there is nothing more to do. Changes were done in  #1692 :

ConnectionRequest is a Node to Node routing message sent viw RMD, and ConnectionResponse is a DirectMessage sent via quic_p2p.
