### ISSUE TITLE
Tracking peers based on connectivity or just via msg signatures

### ISSUE THREAD

**Issue by Lindsey17** [maidsafe/routing#1687]
=> Related to decoupling of different layers

=> Let’s assume PeerManager is replaced by a simpler Map<PublicId, Endpoint>. there won't be a one-to-one immutable mapping from a peer to an endpoint. The Messages signatures will associate them to a specific sender.

=> Without this, we would need a routing level handshake to negotiate routing identities are they don’t tie to network layer identities

=> Heartbeats also tie into this as elders must ensure adults stay responsive

**Comment by dirvine** [comment]
>. A peer won’t be associated to a socket
If we had Map<PublicId, ScocketAddr>. then it would.

**Comment by pierrechevalier83** [comment]
> A peer won’t be associated to a socket
> If we had Map<PublicId, ScocketAddr>. then it would.

I agree the wording is a bit strange. I think what was meant that there isn't a permanent association between a peer and its endpoint. Any message will contain the sender's public ID and that will allow remapping of the endpoint if it has changed.

So it is more like: there won't be a one-to-one immutable mapping from a peer to an endpoint.
