### ISSUE TITLE
Decide what to do about the #[ignore]d tests due to bootstrap blacklist missing in quic-p2p

### ISSUE THREAD

**Issue by madadam** [maidsafe/routing#1694]
quic-p2p doesn't support bootstrap blacklist yet, so some tests that relied on it were `#[ignore]`d. Decide what to do about them: either implement bootstrap blacklist in quic-p2p and then remove the `#[ignore]` attribute, or modify the tests to not require bootstrap blacklist (perhaps by converting them to unit tests - similar to the tests in `src/states/elder/tests.rs`) or remove them.

**Comment by dirvine** [comment]
Not needed for Fleming So " modify the tests to not require bootstrap blacklist" is the best route here

**Comment by Lindsey17** [comment]
Resolved by PR #1698
