### ISSUE TITLE
memory leak somewhere

### ISSUE THREAD

**Issue by eminence** [maidsafe/routing#1700]
Hi all,

I've been poking around this repository to try to use it for a personal project that needs a storage DHT.  

I'm using the `fleming` branch, and have a test executable that's very similar to the key_value_store example (my version hardcodes a local bootstrap node and doesn't construct a client).  In my test, I have a two nodes -- one is the first node in the network and the second joins it.  The two nodes connect to each other successfully, and then they sit idle at about 0% CPU and about 200MB memory each.

After letting them idle for about 10 hours, both processes are using between 20% and 40% CPU, and both processes are using 15GB of memory.   The memory growth is highly non-linear.  At the time of this writing, the memory usage of both processes is growing at about 2 megabytes per second.

I realize this branch is still in very active development, so I understand that things are in a state of flux.  But I wanted to open this issue to let you know about this issue.  

Thanks!

**Comment by dirvine** [comment]
Thank you for the report. At the moment the PARSEC graph is not pruned at all and will grow, but nice to have this report to remind us of this.  We should have this tackled as pruning is possible as we take events to a chain that can be store on disk and is very much smaller.

**Comment by madadam** [comment]
Parsec pruning was implemented in #1786, #1789 and #1798. Closing.
