### ISSUE TITLE
Store our_history position in their_knowledge (Optional ?)

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/routing#1722]
(init est: 1-2 days)

currently their_knowledge store a SectionInfo version that is only accidentally related to the our_history block containing the associated BLS Key.

Add an `iter_blocks()` function on SectionProofChain that iteratate over SectionProofBlock
Add an accessor for the BlsPublicKey in SectionProofBlock

Convert the SectionInfo into a BlsPublicKey in handle_ack_message_event.
Then use the `position()` of the iterator that match the BlsPublicKey instead of the SectionInfo version.

Note:
When BLS is included, security_metadata BLS key will need to be consensused and use as the source to send the AckMessage.

**Comment by madadam** [comment]
Closed via #2099
