### ISSUE TITLE
Epic: Parsec Graph pruning: 

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/routing#1781]
### Parsec Graph pruning: 
  - Is it 2a: Probably.
  - Are we locked in a single parsec No.
  - See Adam + JP section bellow for some additional thoughts.
  - 1st item before splitting: Answer design questions.
  - **Option A**
      - Treat it as a no-op section split (no prefix change)
          - Optimise by being able to reuse keys + SectionInfo
          - Security implications?
  - **Option B**
      - Prune existing graph
      
#### Design for option A

Parsec is currently being reset in `Elder::finalise_prefix_change`
This involves:
- getting a new `GenesisPfxInfo`, cached events and completed events from the chain by calling `Chain::finalise_prefix_change`
- getting unconsensused events from the current Parsec
- initialising a new Parsec in the map and re-voting for the relevant events

This can be used almost unchanged for pruning the graph, as long as we guarantee that the functions are called by everyone at the same point in the chain.

- `Chain::finalise_prefix_change` doesn't really do anything directly related to prefix changes - rather, it returns all the info needed for proper re-voting into the new Parsec, so it could be just renamed to something like `Chain::get_parsec_init_info`
- most of `Elder::finalise_prefix_change` could be extracted to a method like `Elder::prune_parsec` - getting the info from the chain and re-voting on relevant events is unrelated to prefix changes, only a few cleanup calls are related to that

**When to prune:** We need to be careful not to prune while there is an active DKG instance.
The simplest way will be to add a new event to be consensused.

**How to decide to vote for that prune event:**
Can be pretty arbitrary, anything on the routing level. (timer (no), Could be a number of requests/responses, or accumulated serialised byte count from requests+responses - this overestimates the size of the graph and can be spammed, though)

##### Tasks (7-14 days)

- #1784 Detect the right time for prunning + Test. (init 2-4 days).
- #1782 New Prune event with voting for it at the right time + test (maybe). (init 1-2 days)
- #1787 On Prune event, do prune using existing split infrastructure + test. (3-6 big or small? risk - tests start failing (we already do such pruning in splits so should work in prune.))
- #1788 Discard old Parsec instances.
  - Option 1 discard everything but the current one and previous one. (If a node is lagging they will not be able to catch up if prune then split).
    - Can be improved on as needed
    - (1-2 days)
  - Option 2 discard things when no longer needed we know all remaining active nodes are past the previous parsec
    - Complicated.
    - Can hold prunning for as long as not kicked out.
    - (estimate unknown.)
  - Can an attacker force prunning to early and stall everything, for example immediatly detect need to prune and never really progress?
    - Spam not takled now.
    - Probably not quite stalled because prune event needs to go through Parsec.

##### Possible optimisation

The above approach would still do some unnecessary things. For example, if the pruning is unrelated to a prefix change, we don't need to reset cached events in the chain (done by `finalise_prefix_change`) - it should be enough to initialise a new Parsec with a new genesis info and re-vote on unconsensused events (JP - Not sure about that). Thus, a more optimal plan could be:

- extract `Chain::get_new_genesis_info` from `Chain::finalise_prefix_change` that would just create the new `GenesisPfxInfo`
- create (or extract from `Elder::finalise_prefix_change` if possible, but the overlap in functionality might be too small) a method `Elder::prune_parsec`, that would:
    - drain the unconsensused observations
    - get the new genesis info from the chain
    - initialise the new Parsec
    - vote for the unconsensused observations

#### Security considerations

Pruning the Parsec instance loses information about consensused but unaccumulated votes, which opens us up to replay attacks: malicious parties could replay votes that were consensused before in order to make others consider their votes again (would be detected as malice if Parsec wasn't pruned)

- unclear: is that unsafe? The votes would be duplicates, anyway - if the event voted on was kept in the chain, that wouldn't add any new votes. If it was pruned for some reason (didn't accumulate and got dropped), the accumulation would start anew, but the malicious actors still wouldn't be able to make it accumulate by themselves.
- could be prevented by keeping a set of hashes of consensused observations (Fraser's suggestion) - that would have to be extracted from the old Parsec and input on initialisation into the new Parsec
- we could also use the chain here - make it keep all the consensused votes and check for duplicates there - but would it be the right place to do it? probably not

**Comment by Lindsey17** [comment]
Includes issues #1782 & #1784

**Comment by jlpell** [comment]
Where is the best place to fine more background information on why the Parsec graph needs to be pruned, and what pruning accomplishes?

**Comment by jeanphilippeD** [comment]
@jlpell sorry, I missed that. There is not really background information, it was a known aspect that Parsec keeps a full history of all the messages that occurred and so take up more and more memory. If we did not recover that memory we would run out and crash. What pruning does is discard the part of the information we do not need to keep and thus keep the memory consumption under control.

**Comment by jeanphilippeD** [comment]
All linked issues are closed, thus completing this epic.
