### ISSUE TITLE
Consts required for node age 

### ISSUE THREAD

**Issue by dirvine** [maidsafe/routing#1808]
We will define some const values to allow node age to calculate the section membership and node Persona's. These are as follows 

`SAFE_SECTION_SIZE :u8 = 100`
`ELDER_SIZE :u8 = 7`

Note (thanks @ustulation ) that a split occurs when we can guarantee SAFE_SECTION_SIZE per new section. 

These const values are used to determine a nodes persona when we split the section. Routing will add nodes up to the `SAFE_SECTION_SIZE` but then the consumer of routing (Vaults in SAFE case) will request to add new nodes as the existing nodes become full or otherwise incapable. Whether the consumer indeed wishes a node `Killed` or just to leave it full is the choice of the consumer library.

**Comment by ustulation** [comment]
Should the split size be little over 2*safe-sec-size to prevent losing a node and needing a merge to get back to safe-sec-size invariant ?

**Comment by dirvine** [comment]
Ah, nice catch @ustulation  that is supposed to be not 200, but 100 at least per side. I will make that change. In terms of any buffer, the notion is that if necessary (at all times) if we fall below safe_seciotn_size we accept new nodes until we get back up to that.
