### ISSUE TITLE
Re-evaluate visibility of parts of Routing code

### ISSUE THREAD

**Issue by fizyk20** [maidsafe/routing#1824]
Some parts of the Routing code are declared `pub` when they shouldn't be. This breaks unused code detection - things that are `pub` might be used by the library's consumers and so everything they use is considered used, even if these parts of the API shouldn't be directly used by the consumers.

We need to investigate which of the `pub` items can be safely changed to `pub(crate)` (or even entirely private) and apply such changes. The `Chain` can be a good starting point, as it shouldn't be necessary to use it directly from outside the crate.

**Comment by madadam** [comment]
Addressed in https://github.com/maidsafe/routing/pull/1991.
