### ISSUE TITLE
Handle Client Connections

### ISSUE THREAD

**Issue by ustulation** [maidsafe/routing#1832]
Currently, client connections to the routing layer are ignored as can be [seen from here](https://github.com/maidsafe/routing/pull/1830/files/4aeb425ed8204bc9ccea136e2a4761a73b955ce4#diff-5c9e867db5f6281050830fb4b06129f2R126). Once the API for vault <-> routing exchanges has been put, we should pass these client connections up to the vaults (they should handle these and not routing).

**Comment by madadam** [comment]
Closed mostly in #1838
