### ISSUE TITLE
Simplify connection logic

### ISSUE THREAD

**Issue by octol** [maidsafe/routing#1855]
## Overview

The motivation is making connecting / disconnecting simpler and faster.

Group `PublicId` and `ConnectionInfo` into a struct

```rust
struct P2pNode {
    public_id: PublicId,
    conection_info: ConnectionInfo
}
```
Then we should be able to get rid of the `peer_map` and simplify how connections are handled. We consider ourself being connected to a node by having knowledge of their `ConnectionInfo`. This is separate from being connected at the network layers, which is handled by quic-p2p.

## Implemenation steps

- [x] Update enums and structs to carry a `P2pNode` instead of `PublicId` or `ConnectionInfo`.
- [ ] Get rid of dead code once we start replacing `peer_map` lookups with `P2pNode` calls 
- [x] Simplify connection steps, hopefully getting rid of `ConnectionRequest` and `ConnectionResponse`.

**Comment by madadam** [comment]
Closed via #2033.
