### ISSUE TITLE
Optimize relocation

### ISSUE THREAD

**Issue by madadam** [maidsafe/routing#1859]
Currently (when #1848 is merged), the relocation works like this:

1. The section votes to relocate a node
2. When the vote accumulates, they send a routing message (`Section` -> `Node`) to the node to be relocated
3. The node receives the message and uses it, together with its security metadata, as a proof for the target section that the relocation is genuine.

We can optimize it like this:

1. The section votes to relocate a node like before, but each vote now includes a BLS signature share of the relocate details.
2. When the vote accumulates, the sig shares are combined to form full BLS signature. That + the current `SectionBlockChain` is used as the proof for the target section
3. ~~No additional message needs to be sent to the node-to-be-relocated, because that node too receives the accumulated vote and can act on it~~
If the node to-be-relocated is elder, it will also receive the vote, so no additional message needs to be sent to it. Otherwise a simple `DirectMessage` with the relocate details + the signature and proof is sent to it.
4. The remaining nodes can then immediately remove and disconnect the relocated node. There is no need for the delayed disconnection hack we currently use as there are no more messages sent to the node

**Comment by jeanphilippeD** [comment]
> 3. No additional message needs to be sent to the node-to-be-relocated, because that node too receives the accumulated vote and can act on it

Only true for Elder, for Adults still need to send the message. So could do that for both Elder and Adults, however that message do not need to be SMD, only a single DirectMessage suffice.

**Comment by madadam** [comment]
> Only true for Elder

Are you sure about this? Adults (and infants) also have parsec and chain, so can also receive accumulated events.

**Comment by jeanphilippeD** [comment]
> Are you sure about this? Adults (and infants) also have parsec and chain, so can also receive accumulated events.

If nobody gossip to them then they get nothing. that parsec is waiting for someone to send something, but Elder will not send anything until they vote them as Elder or as Dkg participants.

**Comment by madadam** [comment]
That's true. Then yes, we need to send a `DirectMessage` to the relocated node, unless it is elder.
