### ISSUE TITLE
Tackle the disconnect part of Remove ConnectionRequest/Response pattern and PeerMap work

### ISSUE THREAD

**Issue by maqi** [maidsafe/routing#1875]
This is a split off issue from the work of [PR 1865 Remove ConnectionRequest/Response pattern and PeerMap](https://github.com/maidsafe/routing/pull/1865) to tackle the disconnect part.

It also remove the last use of send_connection_request Allowing to remove ConnectionRequest, and prepping the work to remove ConnectionResponse.

So far we only have elder and want to deal with disconnection when using the Responsiveness Tracking.
When we will want to deal with Adult, probably a different mechanism will be required.

**Comment by madadam** [comment]
Closed via #2033 and #2050 .
