### ISSUE TITLE
Add Node API to get elders in a closest section

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/routing#1902]
`routing::Node` should expose a public method to get connection info for elders in a section that's closest to the provided `XorName`. This is required by Vaults to respond to clients trying to join their section.

We can reuse the code from the `Rebootstrap` response: https://github.com/maidsafe/routing/blob/076ed5c810e70a36ff12acb7c5dd244697b149e7/src/states/elder/mod.rs#L772-L778

**Comment by madadam** [comment]
Closed in https://github.com/maidsafe/routing/pull/1915
