### ISSUE TITLE
Handle own section info separately from neighbour info + remove merge logic

### ISSUE THREAD

**Issue by madadam** [maidsafe/routing#1904]
They are both currently handled in one function (`handle_section_info_event`) even though they are quite different, which makes the code unnecessarily complex and confusing.

Also remove the last remaining bits of the merging logic which is non-functional anyway and only clutters the code.

**Comment by jeanphilippeD** [comment]
To clarify, not just `handle_section_event`, but clean up all
```
            AccumulatingEvent::SectionInfo(ref info, _)
            | AccumulatingEvent::NeighbourInfo(ref info)
```
that should not really be handled using the same code.
