### ISSUE TITLE
Change the MemberKnowledge message from periodic to event-driven

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/routing#1952]
The `MemberKnowledge` message is currently sent periodically every 2 seconds. This generates lot of unnecessary traffic. We should change it so the message is sent only when the knowledge actually changes. We need to be careful to handle edge cases though. Consider this:

- A section splits and the set of elders in one of the sub-section doesn't have any node in common with the set of elders pre-split.
- That means the there is no node that sends parsec gossip to the newly promoted elders, because all the previous elders were already demoted and the new elders don't yet know they were promoted.
- This is fine for now, because the `MemberKnowledge` is sent periodically and so does reach the former elders who then respond with parsec gossip which makes the nodes catch up to their own promotion. 

So any change to the sending logic must handle the above (an similar) situations.

**Comment by madadam** [comment]
Closed via https://github.com/maidsafe/routing/pull/2160
