### ISSUE TITLE
Adults handle BootstrapRequest differently than elder

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/routing#1962]
Adult meant to forward all bootstrap request to elder for proper handling.
However this resulted in a loop for #1929 which was solve with sending Join as well.

The problem remains that Elder do more validation checking before sending a Join response.
We need to clarify code so handling is correct whether an Adult or Elder receives it.

**Comment by madadam** [comment]
There is no validation that elders do and adults/infants don't in the `BootstrapRequest` handling. This might change when we address https://github.com/maidsafe/routing/issues/2021, but until then there is nothing to do. Closing.
