### ISSUE TITLE
Enable Sentinel 

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/routing#201]
Sentinel check is not enabled yet in the current code.

**Comment by mmoadeli** [comment]
1- Currently Sentinel::new requires an implementation of SendGetKeys trait as argument.
2- RoutingNode requires an instance of Sentinel
3- RoutingNode is created using RoutingNode::new method which does not have self
4- an implementaion of SendGetKeys most likely does not have any value. This means that it is not possible to create a lifetimed instance of the SendGetKeys implementation in RoutingNode::new and pass it to Sentinel::new

Considering above four, the implemention of SendGetKeys seems needed to be done before and passed to RoutingNode::new.
It will be ugly as below

```{
   let test_send_get_keys = TestSendGetKeys::new();
   let rouing_node: RoutingNode::new(test_send_get_keys, other params)
   work on rouing_node
}```

instread of 
```{
   let rouing_node: RoutingNode::new(params)
   work on rouing_node
}```

Potential conclusion: sentinel needs a little work to be easily used in routing_node

**Comment by dirvine** [comment]
Sentinel under rewrite at moment in it's own lib I am going over design at 15:00 today with Brain and Ben, it would be good to delay this task till after that at least and get one of those guys to help as they will be steeped in sentinel workings. Maybe even a new sentinel

**Comment by mmoadeli** [comment]
Ok. I will start another task then.

**Comment by benjaminbollen** [comment]
started by https://maidsafe.atlassian.net/browse/MAID-1042
