### ISSUE TITLE
put_own_public_pmid should be issued only after knowing the id of the bootstrap node

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/routing#203]
put_own_public_pmid should be issued only after knowing the id of the bootstrap node. All messages sent out needs to know bootstrap node’s id, so that they can populate the Source address correctly. We need to block in bootstrap method until bootstrap node’s id is known.

**Comment by mmoadeli** [comment]
please see the pull request for more information
https://github.com/dirvine/routing/pull/214

**Comment by benjaminbollen** [comment]
Dealt with in address_relocation
