### ISSUE TITLE
Routing improvements.

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/routing#2032]
All improvements suggested by @dirvine during meeting.

- [ ] Don't pass certificates to quic #2034 
- [ ] Pass 2 event types to quic-p2p, one for bi-directional (clients) and one for uni-directional (p2pnode)
- [ ] use `SocketAddr` and keep that in the type we use for Nodes
- [ ] Change all the `our_info` etc. to reflect what it is (i.e `SectionChain`). Kill SharedState from being too large.
- [ ] Have no neighbors, only local section and remote sections.
- [ ] Only target sections and never prefixes. 
- [ ] Add their SectionKey to messages that target a section. This allows remote sections to update our version of the section key/info (such as elders `SocketAddr`). Note this means SharedState is too aggressive and complex
- [ ] Have the threshold in BLS set at PARSEC quorum (at min over 50% to prevent double-voting etc.)
- [ ] non-responsive checks must be robust and then base parsec history on that
- [ ] Confirm when stuff has PARSEC agreed it's also section signed
- [ ] Single message structure with variants all confirmed and fully designed
- [ ] Error handling improvements, don't just pass errors up, try and fix them etc.

cc @madadam

**Comment by S-Coyle** [comment]
Logged each relevant item individually, issue numbers range from 2039 - 2048
