### ISSUE TITLE
routing_client::run() should be internal and not public

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/routing#204]
routing_client::run() needs to be internal to routing and upper layer should not have any control on this. This should be called inside bootstrap method (non public method). This method allows routing to accept messages from crust.

This PR actually made run public method. https://github.com/dirvine/routing/pull/200
Not reverting the PR as its merged and other parts of the PR are valid.

similar to routing node task https://github.com/dirvine/routing/issues/202

**Comment by maqi** [comment]
this will requires RoutingClient spawning a thread to waiting for the event from channel and call proper handler,
the patten will be similar to the pattern in ConnectionManager but not easy to fit in for RoutingClient.

**Comment by maqi** [comment]
If this https://github.com/dirvine/routing/pull/221 is a valid way to resolve the issue,
then I will continue with #202 using the same pattern

**Comment by chandraprakash** [comment]
Myself and Peter had a discussion on this approach. We didn't reach a conclusion. And this task was then deferred till end of this iteration.

**Comment by benjaminbollen** [comment]
This issue will be addressed in https://maidsafe.atlassian.net/browse/MAID-1057

It is important to avoid wrapping these mutable ownership structures in Mutexes; it negates the point of a reactive pattern.

**Comment by benjaminbollen** [comment]
Client currently keeps an external event loop; event loop for routing node has been internalised
