### ISSUE TITLE
Message signatures sent to a lagging node might fail to accumulate

### ISSUE THREAD

**Issue by madadam** [maidsafe/routing#2059]
Related to #1941 

Consider this scenario:

1. Section splits, but one node lags behind
2. The section wants to send a section-signed message so it sends the message signatures
3. One of the signature targets is the lagging node
4. The lagging node receives the signatures, but does not recognize the senders, so it rejects them
5. We assume at least one of the signature targets is honest, so if it happens to be the lagging node we might fail to accumulate the message

Possible fix:

- (simplest): Accumulate the signature even if we don't recognize the sender. But we should consider whether this has any security implications
- Check the message proof. If it is valid, accumulate. If it is too new, backlog and try again on the next SectionInfo. Otherwise reject.

**Comment by dirvine** [comment]
>The lagging node receives the signatures but does not recognize the senders, so it rejects them

I think this is where we miss an important trick. The receiver should send back an error with the message and force the sender to update our info, i..e they should be ending the chain part we need. It's better that trying to force a mechanism where all nodes are in sync as it should be perfectly fine they are not, but hte network can still progress.

**Comment by madadam** [comment]
Fixed by accepting the signature even if we don't recognize the sender. Raised separate issue #2064 to address the security implications of doing so (if any).
