### ISSUE TITLE
 Change NeighbourInfo sending and receiving to not require accumulation

### ISSUE THREAD

**Issue by madadam** [maidsafe/routing#2127]
With #2122, we don't need to synchronize message signature sending via parsec anymore, so we can remove the `SendNeighbourInfo` event and just send the message directly. With #2110 the info is already signed so we don't even need to go through signature accumulation anymore. We just need to provide sufficient proof and send it as `Node` -> `Section` or `Node` -> `Node` message. This would require a change to `Message` to allow attaching proofs also to `src:Node` messages.

**Comment by maqi** [comment]
Addressed by https://github.com/maidsafe/routing/pull/2165
