### ISSUE TITLE
Need to have CborError implement Error trait

### ISSUE THREAD

**Issue by dirvine** [maidsafe/routing#241]
To allow us to use cause for routing errors where cause is cbor

**Comment by inetic** [comment]
@dirvine I believe this is the problem we've had that you can't implement a trait R (in our case Error) to type T (in our case CBorError) if neither of them is defined in our library (in our case routing). In rust they seem to call it "the coherence rule"

https://internals.rust-lang.org/t/implementing-a-trait-for-a-type-that-don-t-know-about-each-other/1656

**Comment by dirvine** [comment]
Yes I believe it is. I will close this issue Peter. Thanks for looking.
