### ISSUE TITLE
Unable to detect bootstrap connection on non-Windows platforms

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/routing#244]
On non-Windows platforms, Crust reports the listening endpoint as being `127.0.0.1:port` whereas when a node connects to this endpoint, it reports it using the internal IP (e.g. 192.168.0.34:port).  This is causing an issue when we try to detect if we are about to try and duplicate the bootstrap connection.

We aim to avoid duplicating the bootstrap connection, so when we receive a ConnectResponse mesasge, where we would normally connect to the peer, we look to see if we are already connected.  We should only be connected already if the peer is the node we bootstrapped off.  So we want to check if our bootstrap peer's endpoint == one of this peer's endpoint vector, then we don't try and connect again.  This comparison fails since the IPs aren't equal.

**Comment by rossmuir** [comment]
On the LAN test when stopping a Windows node all other nodes know about it `handle_lost_connection_event peer_ep`, when stopping a Linux node this is not the case.
Linux nodes will see another node lost if it is on the same machine `handle_lost_connection_event peer_ep : Tcp(V4(127.0.0.1:60539))` - should this be a separate issue or can this be added here?

**Comment by benjaminbollen** [comment]
reported as corrected by CRUST
