### ISSUE TITLE
Send Findgroup if we lose a close group node

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/routing#252]
Send FindGroup if we lose connection to a close group node

**Comment by benjaminbollen** [comment]
Can we not extract updates on our close group from swarmed messages?

**Comment by chandraprakash** [comment]
I guess, on any routing table change, just check if the node which went down was close group member and fire a findgroup and forget.

**Comment by benjaminbollen** [comment]
Messages are filtered on new interesting nodes;

nodes should primarily be dropped as "online" when connected node is lost; when the whole group agrees to drop the node, we should trigger a churn event
