### ISSUE TITLE
Unauthorized Put and Get (of Session Packet atleast) does not need (or even have) signature.

### ISSUE THREAD

**Issue by ustulation** [maidsafe/routing#270]
<1> https://github.com/maidsafe/routing/blob/master/src/messages.rs#L156
`private_sign_key : &crypto::sign::SecretKey` should be `private_sign_key : Option<&crypto::sign::SecretKey>` because i don't even have these while trying to fetch the Login Packet.
<2> `RoutingMessage` needs to have Signature as `Optional`
<3> https://github.com/maidsafe/routing/blob/master/src/routing_client.rs#L165 needs to have a construcor that takes nothing and generates random id as the address of client machine - because again there will be situations i wont have stuffs which are required by the present constructor.

This is coming from my understanding of client so far - so not sure.

**Comment by benjaminbollen** [comment]
@ustulation are these still up to date?

1. create a throw-away key if un-needed
2. we keep the signature present everywhere just now, to not have to differentiate; I'll keep this issue open for this
3. I am (still) under the assumption that maidsafe_client wants to be able to pass in keys specifically on routing_client construction

**Comment by ustulation** [comment]
No this is not entirely up to date anymore in the sense that `<1>` is already being done by `maidsafe_client`. But what is still the issue is the `<2>` nd point that you mentioned. maidsafe_client does not really bother about signatures, but i saw that is what is happening in routing and from what i gathered GETs and unauthorised PUTs don't need signatures. So this is independent of client crate and thus not urgent or necessary for client - thus can be further discussed or closed or resolved.

**Comment by benjaminbollen** [comment]
Unauthorised put s dont exist anymore; and every request is now signed
