### ISSUE TITLE
Need to use Types

### ISSUE THREAD

**Issue by ustulation** [maidsafe/routing#271]
https://github.com/maidsafe/routing/blob/master/src/routing_client.rs#L66

Constructor needs to take in types of type MaidSafe-Types instead on internals - Sort of more object-oriented.

**Comment by inetic** [comment]
@ustulation , can you you elaborate please? Which types should be replaced by which? Also, is this still relevant? Because there is now the new routing_client_new::RoutingClient which doesn't seem to use the ClientIdPacket.

**Comment by ustulation** [comment]
ya this is pretty old and now with the new issue raised this one is invalidated so can be closed. Thanks @inetic
