### ISSUE TITLE
Descriptive Example name

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/routing#274]
Can the example name `routing`  be updated - to make it clear what the example does.

**Comment by benjaminbollen** [comment]
Are you happy with 'SecureKeyValueStore' or is that too unimaginative.  Not all features are there to call it secure either, but that is what it should be after the sprint.

**Comment by rossmuir** [comment]
I think it should still have the library name included in some way as all examples will be bundled together to help the end users identify them  ...so 'Routing-SecureKeyValueStore' ?

**Comment by benjaminbollen** [comment]
Maybe Routing_KeyValueStore

**Comment by rossmuir** [comment]
Good for me - thank you

**Comment by benjaminbollen** [comment]
called simple_key_value_store
