### ISSUE TITLE
Issues with simple_key_value_store help output

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/routing#315]
Running `-h` yields:

>     Usage:
      routing_new [--type=<node_type>] [--peer=<end_point>]
      routing_new (-h | --help)

>       If no arguments are passed, this will try to connect to an existing network
      using Crust's discovery protocol.  If this is unsuccessful, you can provide
      a list of known endpoints (other running instances of this example) and the node
      will try to connect to one of these in order to connect to the network.

>     Options:
      -h --help           Show this screen.
      --type=<node_type>  node_type = client | node | first.
      --peer=<end_point>  end_point

* The binary's name is no longer `routing_new`
* The term "client" was removed entirely from the Crust example to avoid giving the impression of a client/server network - this may be a requirement here too.
* There's no need to have `--peer` since any endpoints passed can only be peers (c.f. Crust example)
* `end_point` should be `endpoint`
* Except for `-h`, the descriptions for the options aren't descriptive (c.f. Crust example)
* Validation of `node_type` isn't being set, e.g. you can successfully call `--type=a`.  I'd suggest doing away with the `--type` arg as well and change the Usage part to:

        simple_key_value_store [--client | --node | --first] [<peer>...]
        simple_key_value_store (-h | --help)

* The description doesn't say which value for `type` will be chosen if no args are passed.

**Comment by mmoadeli** [comment]
I started working on this
