### ISSUE TITLE
Routing 0.1.62 Id type change causes problem

### ISSUE THREAD

**Issue by ustulation** [maidsafe/routing#336]
think with the present code `client` will not be able to work with the new `Id` thing in routing.
`maidsafe_client` requires this to be present in the session packet (along with mpid groups) and also to encrypt/decrypt DirectoryListings etc.

It contacts `maidsafe-types` for that

`maidsafe_types` does the random symmetric and asymmetric key-pair generations

`maidsafe-types` has no provision to construct it from given keys - it is who generates it - see:
https://github.com/maidsafe/maidsafe_types/blob/master/src/id/revocation_id_type.rs#L67
for example

And that is how i think it should be - generation of secure keys in `types` library so that there is one place to go to if someone wants to audit/tinker it and also fits with the paradigm of maidsafe-types crate itself.

`routing` should not be the one generating keys - it should accept it in a package (like clientid stuff previously) and then do what ever it wants.

Anyway - unless types crate is changed it will break `client` as of now.

**Comment by s-brian** [comment]
PR for this issue at https://github.com/maidsafe/routing/pull/337.

**Comment by benjaminbollen** [comment]
maidsafe_client can use the new constructor "with_keys" to construct routing::types::Id to pass into the constructor of routing::routing_client
