### ISSUE TITLE
Use the recently create Refresh message in routing membrane

### ISSUE THREAD

**Issue by inetic** [maidsafe/routing#362]
Currently routing membrane uses Put message for this purpose.

**Comment by inetic** [comment]
Ben, I was thinking about the Sendable trait and came to realize we'll be much better off without it. Really what we need out of it is just the `type_tag` and the `name` values, both of these can be easily passed [to the `refresh` function](https://github.com/maidsafe/routing/compare/master...inetic:refresh-without-sendable-trait?expand=1#diff-647ebc1293551c577c303914f4c91ce6R839). It has few advantages, the fist one is that we won't need to clutter all our structures with another template parameter (not only the RoutingNode and RoutingMembrane would need this, but also the MethodCall::Refresh enum, and who knows what else). The second advantage is that it will allow us to avoid the double parsing as the type tag is now contained inside the routing::Refresh message and it can be passed to the interface easily.

I made some progress using this approach that you can have a look here:

https://github.com/maidsafe/routing/compare/master...inetic:refresh-without-sendable-trait?expand=1

It tries to make use of the RefreshAccumulator, but the interaction with the interface is still a TODO:

https://github.com/maidsafe/routing/compare/master...inetic:refresh-without-sendable-trait?expand=1#diff-647ebc1293551c577c303914f4c91ce6R573

**Comment by dirvine** [comment]
I tend to agree here, I think refresh is pretty specific and also will not need keys checked as the closeness is already confirmed by routing. So a simpler faster accumulator configuration is in fact all that may be required here.  As long as routing confirms you are in the group you claim to be sending from and of course it only sends back to the correct group itself, then we are safe.

**Comment by benjaminbollen** [comment]
Seems good to me

**Comment by benjaminbollen** [comment]
would need a key-field, a NameType though?

**Comment by inetic** [comment]
Sorry, could you be more specific? Where exactly would you like the added NameType?

**Comment by benjaminbollen** [comment]
addressed already; in Refresh message

**Comment by benjaminbollen** [comment]
superseded by #363
