### ISSUE TITLE
Implement an ad-hoc accumulator for the recently created Refresh message

### ISSUE THREAD

**Issue by inetic** [maidsafe/routing#363]

**Comment by benjaminbollen** [comment]
request-key for temporary accumulator should be (T::name, T::type_tag) where T: Sendable; and before even adding a new 'claim' to this accumulator we have to make sure that from header 'header.from_group().unwrap() = group_name =T::name = header.destination.dest

so it has to come from a group; those three fields have to be identical (and our Authority should then be OurCloseGroup); so to check these three fields are identical use the 'our_authority' function available and assert that it returns 'OurCloseGroup' where element is T::name

**Comment by inetic** [comment]
If there were these nodes in the group {A, B, C, D} and each node would see the group a little different. E.g. A would see {A,B,C,D}; B would see {A,B}; C would see {A,B,C} and D would see {A,D}. Wouldn't the message_header.from_group be different in some of the cases?

**Comment by dirvine** [comment]
They would all see slightly different nodes for sure, but the same number of them I would think.

**Comment by inetic** [comment]
Wouldn't it then be a problem to group by `from_group`? Then each time a message arrived it would be grouped by a different key.

**Comment by dirvine** [comment]
Only if the group address was different. You will get definitely QUORUM number of matching keys in response. The group key is a bad name it's a group address really, so each node close to the address send what it thinks are the closest nods to it. .

**Comment by benjaminbollen** [comment]
the from_group is identical to the name field, for every node concerned
