### ISSUE TITLE
simple_key_value_store crashes if command issued during bootstrap

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/routing#370]
On starting the example with no args on Windows, I get the output:

>     Enter command (stop | put <key> <value> | get <key>)>
    trying to bootstrapped client

(The second line should be made into a proper sentence).

At this stage, a "put" command yields:

>     Putting value of "b" to network under key "a".
    thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', C:/bot/slave/nightly-dist-rustc-win-gnu-64/build/src/libcore\option.rs:362

Likewise a "get" command yields:

>     Getting value for key "a" from network.
    thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', C:/bot/slave/nightly-dist-rustc-win-gnu-64/build/src/libcore\option.rs:362

Due to the similarity of these errors, I have filed this as a single issue.  If needed, I can split this into two separate issues if it becomes apparent that they're unrelated.

**Comment by southsideGLA** [comment]
I get similar on Ubuntu 15.04 with the latest git update

<willie@gagarin:~/projects/MaidSafe/routing/target/debug/examples$ ./simple_key_value_store 
Enter command (stop | put <key> <value> | get <key>)>
trying to bootstrapped client

Invalid command.
Enter command (stop | put <key> <value> | get <key>)>
put PaisleyS MhairiBlack
Putting value of "MhairiBlack" to network under key "PaisleyS".
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:362
>

**Comment by benjaminbollen** [comment]
Likely relates to #388; being addressed; check if resolved when this issue is merged

**Comment by Fraser999** [comment]
I don't know if this got auto-closed or was closed by accident, but I guess it should stay open until we know it's resolved.  I'll re-open for now.  If it's resolved, @benjaminbollen  can you add a comment please?

**Comment by benjaminbollen** [comment]
I've not encountered this error anymore; that s why I closed it

**Comment by benjaminbollen** [comment]
this is resolved some time ago; if a new error occurs it deserves a new issue
