### ISSUE TITLE
Carry over / write unit tests for routing_membrane

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/routing#372]

**Comment by benjaminbollen** [comment]
start a new issue for the specific part that you address, as this is a big chunk of work.

Feel free to improve where you see fit, or just copy close to the original as a first approach

**Comment by mmoadeli** [comment]
I put the effort initially on carrying over the existing tests to routing_membrane. Once done, I think of potentially adding more tests.

**Comment by benjaminbollen** [comment]
good

**Comment by mmoadeli** [comment]
1- Relevant tests are carried over 2- The ones currently failing due to missing code, are implemented but  #[ignored] 3- Maintainers can advise for new tests

**Comment by benjaminbollen** [comment]
Cool thanks Mahmoud, I asked Peter to review and help.

**Comment by mmoadeli** [comment]
assigned to @peter for review

**Comment by mmoadeli** [comment]
I close the issue as it is already merged
