### ISSUE TITLE
simplifies routing_node creation

### ISSUE THREAD

**Issue by mmoadeli** [maidsafe/routing#379]
currently, routing node is created using F(interface) and G(generator). As creation of G(generator) requires F(interface). It makes sense to have only G get passed to create routing_node.
one can access to F, through G::F. in RoutingNode struct.

**Comment by benjaminbollen** [comment]
pausing review till tonight or later as the API change already pauses this issue.

**Comment by benjaminbollen** [comment]
Has been done + reverted = not present; redo in next version
