### ISSUE TITLE
Call to unauthorised-put causes panic

### ISSUE THREAD

**Issue by ustulation** [maidsafe/routing#388]
Calling Unauthorised-put of RoutingClient causes Panic. The call is made from `maidsafe_client`'s `create_account` function here:
https://github.com/maidsafe/maidsafe_client/blob/master/src/client/mod.rs#L106
This causes poisoning of the locked mutex which then causes subsequent panics in other threads sharing the mutex such as this:
https://github.com/maidsafe/maidsafe_client/blob/master/src/client/mod.rs#L98

**Comment by benjaminbollen** [comment]
There is still an unimplemented!() in routing_client-> NewMessage -> PutDataResponse; In the speed I thought we didn't rely on the put_response, but we will get the response back, so an unimplemented, should urgently be removed ! sorry about this!

**Comment by benjaminbollen** [comment]
also removing other lingering unwraps in routing_client.  Sorry during last sprint I didn't focus on routing_client as much as I should have

**Comment by benjaminbollen** [comment]
To be tested in routing network
