### ISSUE TITLE
Cut down swarm traffic 

### ISSUE THREAD

**Issue by dirvine** [maidsafe/routing#389]
To allow network to scale fast swarm needs tamed a little now. I suggest the following rule 

1. A message from our close group to our close group, do not swarm.
2. Filter each such message immediately 
3. Swarm should not alter header info, i.e. no new header it is basically a copy exact message (if we create new message we will get exponential traffic as they all look new)
4. Swarm messages only from outside our close group to us. 

We do need to confirm we get to every node so even nodes that cannot directly speak are caught in swarm (one of the primary purposes). 

At the moment the message numbers will actually saturate the group, affecting lots of actions.

**Comment by afck** [comment]
Fixed in #982.
