### ISSUE TITLE
Testnet doesn't fully connect

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/routing#390]
A network comprised of 30 nodes running via `simple_key_value_store` did not fully connect.

The nodes were split across six remote virtual machines all running Ubuntu and using the Release build of the example.

I believe they should all have had routing tables of size 29.  This is the actual size reported from each node ("#" column indicates order in which nodes were started):

| # | RT Size | # | RT Size | # | RT Size | # | RT Size | # | RT Size | # | RT Size
-----|---------|------|---------|------|---------|------|---------|------|---------|------|--------
0 | 29 | 5 | 29 | 10 | 29 | 15 | 29 | 20 | 28 | 25 | 27
1 | 29 | 6 | 28 | 11 | 28 | 16 | 29 | 21 | 29 | 26 | 29
2 | 28 | 7 | 28 | 12 | 29 | 17 | 29 | 22 | 29 | 27 | 28
3 | 28 | 8 | 29 | 13 | 29 | 18 | 29 | 23 | 29 | 28 | 27
4 | 29 | 9 | 29 | 14 | 29 | 19 | 29 | 24 | 29 | 29 | 28

I don't think this is a routing table issue - the routing table unit tests are pretty comprehensive and show that it doesn't start rejecting additions until the size is above `OPTIMAL_SIZE` which is 64.

**Comment by benjaminbollen** [comment]
I believe this has to do with the put_public_id - or at least it should; the reasoning is: if a new node puts it's Id; it will be relocated, but then the existing nodes need to cache this Id (as received through the network/Sentinel);  It might be that there is a lag on this process completing and as such  node x+2 will find that node x+1 has not connected on time to cache from the network the id of node x+2;

There is currently a patch that opens up an important security flaw and would allow node x+1 to accept the connection from node x+2, despite it not having the Id from the network cached.  It might be however that there is a bug in this bad-patch, such that they actually do not connect.

**Comment by benjaminbollen** [comment]
This will need to be re-evaluated on publishing of routing v0.3.0

**Comment by benjaminbollen** [comment]
this is validated to reliably succeed
