### ISSUE TITLE
CI Travis fails on unstable features used

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/routing#394]
Travis CI fails on CRUST for not allowed unstable feature Arc<Mutex< >>

Jenkins CI works - on rust nightly
Travis is on rust Beta; however what caused the sudden change?

**Comment by dirvine** [comment]
As crust use feature gated code and we depend on it I thought we require nightly

**Comment by Viv-Rajkumar** [comment]
maidsafe/crust#149

**Comment by vinipsmaker** [comment]
@Viv-Rajkumar:
> maidsafe/crust#149

maidsafe/crust#149 should be fixed, but [Jenkins is still unhappy](https://github.com/maidsafe/crust/pull/151#issuecomment-113598171).

**Comment by Fraser999** [comment]
I've recommended that maidsafe/crust#149 should be merged.  There's an issue with the CI build slaves, not the PR.
