### ISSUE TITLE
make handle_refresh explicit

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/routing#402]
remove ourCloseGroup in favor for explicitly checking from_node is
in our close group for handle_refresh

**Comment by inetic** [comment]
I don't mind this change, but I'm curious what is the key of recognizing when a condition is worthy of having its own authority name and when not.

**Comment by dirvine** [comment]
IMHO I think this is an explicit group for an explicit call (refresh), so it can never be any other Authority. In other Authority calls that is passed up to upper layers to decide what to do, but `refresh` is explicit and must be destined for your group from your group. So in refresh we implicitly check Authority.

**Comment by benjaminbollen** [comment]
this work has been done; OurCloseGroup has been removed from our_authority;

handle_refresh will need an explicit check on only receiving the message from RT connections; this is a new task
