### ISSUE TITLE
simple_key_value_store  - put works fine but get returns no output

### ISSUE THREAD

**Issue by southsideGLA** [maidsafe/routing#411]
a small niggle... 
Latest git - all other libraries up to date as of 14:00 22/06/15 with latest nightly rust

willie@gagarin:~/projects/MaidSafe/routing$ cargo run --example simple_key_value_store
     Running `target/debug/examples/simple_key_value_store`
Enter command (stop | put <key> <value> | get <key>)>
trying to bootstrapped client
NOTE: Transport connect 127.0.0.1:56145 failure due to Connection refused (os error 111)
<snip>
NOTE: Transport connect [::1]:42853 failure due to Connection refused (os error 111)

Invalid command.
Enter command (stop | put <key> <value> | get <key>)>
put foo bar
Putting value of "bar" to network under key "foo".
Enter command (stop | put <key> <value> | get <key>)>
get foo
Getting value for key "foo" from network.
Enter command (stop | put <key> <value> | get <key>)>
stop
willie@gagarin:~/projects/MaidSafe/routing$

**Comment by benjaminbollen** [comment]
Can you confirm that you are running a handful of other nodes (on the same machine, unless you have a bootstrap list set up)?  In a bug-fix last friday we cleaned the client such that it would not hard-terminate if it failed to connect and act on a network; but right now as a user you might get not clearly see that the client has no network to act on.

try running - each in a separate terminal:

cargo run --example simple_key_value_store -- --first
cargo run --example simple_key_value_store -- --node
cargo run --example simple_key_value_store -- --node
...
cargo run --example simple_key_value_store -- --node

then run 
cargo run --example simple_key_value_store
to start a client that can act on a network

**Comment by southsideGLA** [comment]
Benjamin, 
 Sorry for the delay, just back in and only now seen your reply

I ran the commands above with the latest git updates for routing

for the final --node command I got this output

willie@gagarin:~/projects/MaidSafe/routing$ cargo run --example simple_key_value_store -- --node
     Running `target/debug/examples/simple_key_value_store --node`
NOTE: Transport connect [::1]:49080 failure due to Connection refused (os error 111)
NOTE: Transport connect [::1]:57183 failure due to Connection refused (os error 111)
BOOTSTRAP to Tcp(V4(192.168.100.100:49080))
NODE listening on Some(Tcp(V4(127.0.0.1:48917)))
Waiting for responses from network
NewConnection on Tcp(V4(192.168.100.100:49080)) while waiting on network.
NewConnection on Tcp(V4(127.0.0.1:57183)) while waiting on network.
NewConnection on Tcp(V4(127.0.0.1:49080)) while waiting on network.
NewConnection on Tcp(V4(192.168.100.100:57183)) while waiting on network.
Enter command (stop)>

and then when I run 
willie@gagarin:~/projects/MaidSafe/routing$ cargo run --example simple_key_value_store 
     Running `target/debug/examples/simple_key_value_store`
Enter command (stop | put <key> <value> | get <key>)>
trying to bootstrapped client
NOTE: Transport connect [::1]:53632 failure due to Connection refused (os error 111)
bootstrapped client
Sending connect requestI expect are

Invalid command.
Enter command (stop | put <key> <value> | get <key>)>
put foo bar
Putting value of "bar" to network under key "foo".
Enter command (stop | put <key> <value> | get <key>)>
get foo
Getting value for key "foo" from network.
Enter command (stop | put <key> <value> | get <key>)>

Again I can **put** a value but am unable to **get** it back
The [::1] failures will be due to me having no IPv6 set up on this LAN

**Comment by benjaminbollen** [comment]
from the output it looks like the (last) node is not connecting to the network either.  Am I correct to assume you started with a --first node?

**Comment by southsideGLA** [comment]
Yes - first command was 
willie@gagarin:~/projects/MaidSafe/routing$ cargo run --example simple_key_value_store -- --first
     Running `target/debug/examples/simple_key_value_store --first`
ZERO listening on Some(Tcp(V4(127.0.0.1:52875))), named c43a50..9e3014
Enter command (stop)>
Started Membrane loop

**Comment by benjaminbollen** [comment]
Nice one ! thanks !

**Comment by benjaminbollen** [comment]
does "get key" also work for you?  -  We recenty added a PutResponse that also replies the original data in the example;

**Comment by southsideGLA** [comment]
It didnt late last night - too tired to respond here at the time - I'll check again with the latest updates from today

**Comment by southsideGLA** [comment]
Seems to work fine with latest git
I ran cargo run --example simple_key_value_store -- --first
then cargo run --example simple_key_value_store -- --node several times in different terminals
and then ...
willie@gagarin:~/projects/MaidSafe/routing$ cargo run --example simple_key_value_store | tee routing-issue.log
     Running `target/debug/examples/simple_key_value_store`
trying to bootstrapped client
Enter command (stop | put <key> <value> | get <key>)>
NOTE: Transport connect 127.0.0.1:53013 failure due to Connection refused (os error 111)
NOTE: Transport connect 192.168.100.100:53013 failure due to Connection refused (os error 111)
NOTE: Transport connect [::1]:53013 failure due to Connection refused (os error 111)
NOTE: Transport connect 127.0.0.1:46083 failure due to Connection refused (os error 111)
NOTE: Transport connect 127.0.0.1:40150 failure due to Connection refused (os error 111)
NOTE: Transport connect 127.0.0.1:41453 failure due to Connection refused (os error 111)
NOTE: Transport connect 127.0.0.1:45425 failure due to Connection refused (os error 111)
NOTE: Transport connect 127.0.0.1:36041 failure due to Connection refused (os error 111)
NOTE: Transport connect 192.168.100.100:36041 failure due to Connection refused (os error 111)
NOTE: Transport connect [::1]:36041 failure due to Connection refused (os error 111)
NOTE: Transport connect [::1]:34023bootstrapped client
 failure due to Sending connect request
Connection refused (os error 111)
received a ConnectResponse from Tcp(V4(192.168.100.100:34023))

Invalid command.
Enter command (stop | put <key> <value> | get <key>)>
put chips vinegar
Putting value of "vinegar" to network under key "chips".
Put sent out with message_id 3244574266
Enter command (stop | put <key> <value> | get <key>)>
received a PutDataResponse from Tcp(V4(192.168.100.100:34023))
Testing client received put_response 3244574266 with testdata TestData(key: chips, value: vinegar)
received a PutDataResponse from Tcp(V4(192.168.100.100:34023))
Testing client received put_response 3244574266 with testdata TestData(key: chips, value: vinegar)
received a PutDataResponse from Tcp(V4(192.168.100.100:34023))
Testing client received put_response 3244574266 with testdata TestData(key: chips, value: vinegar)
received a PutDataResponse from Tcp(V4(192.168.100.100:34023))
Testing client received put_response 3244574266 with testdata TestData(key: chips, value: vinegar)
get chips
Getting value for key "chips" from network.
Get sent out with message_id 3244574267
Enter command (stop | put <key> <value> | get <key>)>
received a GetDataResponse from Tcp(V4(192.168.100.100:34023))
Testing client received get_response 3244574267 with testdata TestData(key: chips, value: vinegar)
put embra_chips salt'n sauce
Putting value of "salt'n sauce" to network under key "embra_chips".
Put sent out with message_id 3244574268
Enter command (stop | put <key> <value> | get <key>)>
received a PutDataResponse from Tcp(V4(192.168.100.100:34023))
Testing client received put_response 3244574268 with testdata TestData(key: embra_chips, value: salt'n sauce)
received a PutDataResponse from Tcp(V4(192.168.100.100:34023))
Testing client received put_response 3244574268 with testdata TestData(key: embra_chips, value: salt'n sauce)
received a PutDataResponse from Tcp(V4(192.168.100.100:34023))
Testing client received put_response 3244574268 with testdata TestData(key: embra_chips, value: salt'n sauce)
received a PutDataResponse from Tcp(V4(192.168.100.100:34023))
Testing client received put_response 3244574268 with testdata TestData(key: embra_chips, value: salt'n sauce)
get embra_chips
Getting value for key "embra_chips" from network.
Get sent out with message_id 3244574269
Enter command (stop | put <key> <value> | get <key>)>
received a GetDataResponse from Tcp(V4(192.168.100.100:34023))
Testing client received get_response 3244574269 with testdata TestData(key: embra_chips, value: salt'n sauce)

Invalid command.
Enter command (stop | put <key> <value> | get <key>)>
stop
willie@gagarin:~/projects/MaidSafe/routing

**Comment by benjaminbollen** [comment]
seems ok to me; closing thanks for double checking !
