### ISSUE TITLE
simple_key_value_store  -  unable to put value 

### ISSUE THREAD

**Issue by southsideGLA** [maidsafe/routing#429]
This is the latest git pull with latest rust nightly. I already have several vaults and clients running on this network.

willie@gagarin:~/projects/maidSafe/routing$ cargo run --example simple_key_value_store |tee routing-latest-commit-eb79898ec8.log
     Running `target/debug/examples/simple_key_value_store`
trying to bootstrapped client
Enter command (stop | put <key> <value> | get <key>)>
bootstrapped client
Sending connect request
received a ConnectResponse from Tcp(V4(127.0.0.1:59637))

Invalid command.
Enter command (stop | put <key> <value> | get <key>)>
put tea "2 sugar"
Putting value of ""2 sugar"" to network under key "tea".
Put sent out with message_id 3596770495
Enter command (stop | put <key> <value> | get <key>)>
received a PutDataResponse from Tcp(V4(127.0.0.1:59637))
Error put_respons: InvalidRequest
received a PutDataResponse from Tcp(V4(127.0.0.1:59637))
Error put_respons: InvalidRequest
received a PutDataResponse from Tcp(V4(127.0.0.1:59637))
Error put_respons: InvalidRequest
received a PutDataResponse from Tcp(V4(127.0.0.1:59637))
Error put_respons: InvalidRequest
received a PutDataResponse from Tcp(V4(127.0.0.1:59637))
Error put_respons: InvalidRequest
get tea
Getting value for key "tea" from network.
Get sent out with message_id 3596770496
Enter command (stop | put <key> <value> | get <key>)>
received a GetDataResponse from Tcp(V4(127.0.0.1:59637))
Testing client received error get_response
received a GetDataResponse from Tcp(V4(127.0.0.1:59637))
Testing client received error get_response
received a GetDataResponse from Tcp(V4(127.0.0.1:59637))
Testing client received error get_response
received a GetDataResponse from Tcp(V4(127.0.0.1:59637))
Testing client received error get_response
received a GetDataResponse from Tcp(V4(127.0.0.1:59637))
Testing client received error get_response
^C
1)  Should this attempt to talk to existing running instances?
2) Error put_respons: InvalidRequest <-- small typo in put_repons - perhaps trivial
3) I will shut sown existing clients and vaults and try again

**Comment by southsideGLA** [comment]
same results when I shut down all other vaults and clients running on the network...

**Comment by benjaminbollen** [comment]
sorry I missed your issue. We are currently testing the routing refactor done during the rust-3 sprint; so will leave your issue open and report back when we have confirmed valid routing behaviour with the new code.

**Comment by benjaminbollen** [comment]
You're welcome to try again with latest routing master
