### ISSUE TITLE
Does not compile with latest git

### ISSUE THREAD

**Issue by southsideGLA** [maidsafe/routing#443]
latest git - rust nightly from this afternoon - Ubuntu 15.04

Command was:
willie@gagarin:~/projects/maidSafe/routing$ git pull && cargo clean --verbose && cargo update --verbose && cargo build  && cargo test --release --verbose |tee update-2110080715.log

...............
src/types.rs:496:28: 496:42 error: failed to resolve. Use of undeclared type or module `Signature`
src/types.rs:496     let validation_token = Signature::new(crypto::sign::sign_detached(&keys, &secret_keys.0));
                                            ^~~~~~~~~~~~~~
src/types.rs:496:28: 496:42 error: unresolved name `Signature::new`
src/types.rs:496     let validation_token = Signature::new(crypto::sign::sign_detached(&keys, &secret_keys.0));
                                            ^~~~~~~~~~~~~~
error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `routing`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name routing --crate-type lib -C opt-level=3 --test -C metadata=94e0210eef6e674b -C extra-filename=-94e0210eef6e674b --out-dir /home/willie/projects/maidSafe/routing/target/release --emit=dep-info,link -L dependency=/home/willie/projects/maidSafe/routing/target/release -L dependency=/home/willie/projects/maidSafe/routing/target/release/deps --extern itertools=/home/willie/projects/maidSafe/routing/target/release/deps/libitertools-f65b66d16fa954e8.rlib --extern rand=/home/willie/projects/maidSafe/routing/target/release/deps/librand-de6cdb9e4fd93d55.rlib --extern cbor=/home/willie/projects/maidSafe/routing/target/release/deps/libcbor-0bd941ffbb5daf77.rlib --extern maidsafe_sodiumoxide=/home/willie/projects/maidSafe/routing/target/release/deps/libmaidsafe_sodiumoxide-ad1479d9e69f0522.rlib --extern time=/home/willie/projects/maidSafe/routing/target/release/deps/libtime-d3937aca0d3022b9.rlib --extern crust=/home/willie/projects/maidSafe/routing/target/release/deps/libcrust-c755017cd3770bd1.rlib --extern docopt=/home/willie/projects/maidSafe/routing/target/release/deps/libdocopt-141ed6b1383f3228.rlib --extern accumulator=/home/willie/projects/maidSafe/routing/target/release/deps/libaccumulator-04b74fd4ede3a1a9.rlib --extern lru_time_cache=/home/willie/projects/maidSafe/routing/target/release/deps/liblru_time_cache-57e7f239582c3efe.rlib --extern bit_vec=/home/willie/projects/maidSafe/routing/target/release/deps/libbit_vec-8d405497b3ca05da.rlib --extern message_filter=/home/willie/projects/maidSafe/routing/target/release/deps/libmessage_filter-1d76f29d63817025.rlib --extern rustc_serialize=/home/willie/projects/maidSafe/routing/target/release/deps/librustc_serialize-c1e8163a38ed3d54.rlib -L native=/usr/local/lib` (exit code: 101)

full output is available at
http://maidsafe.wf.tsone.info/fault-logs/update-2110080715.log

**Comment by rossmuir** [comment]
I can confirm southsideGLA's findings and have labelled this as critical

**Comment by rossmuir** [comment]
@inetic is this being worked? https://travis-ci.org/maidsafe/routing/builds

**Comment by inetic** [comment]
Hi @southsideGLA, we've decided to do some heavy refactoring of routing, that means a lot of API changes. What we did, we create the `0.2` branch, which is now the latest most stable version for other guys to use. We hope to get the stable version to compile soon :)

**Comment by southsideGLA** [comment]
OK thanks - The only thing I can help with really is testing and I know right now Im aiming at a fast moving target.
I'm not sure if the issues I raise are distracting or not and the last thing you guys need right now is well meaning amateurs like me clogging this space.
Im happy to run tests on each crate as it is available on github and submit issues on any failures  IF you think its worthwhile at this time.

I always run 
git pull && cargo clean --verbose && cargo update --verbose && cargo build  && cargo test --release --verbose 
on each crate when ever I see a change on github. 
Tell me what I can do to make this more useful.

**Comment by rossmuir** [comment]
I think it is very useful thank you and I am sure the devs *really* do as well :wink: , I do the same via automated CI and manually as well, your spots help confirm issues and sometimes faster than our systems, so I appreciated it :+1: . One hint (I think you already know this) some libs run tests `RUST_TEST_THREADS=1 cargo test` a quick peek into the `.travis.yml` in each repo will let you know if this is the case (this moves as well :smile:)

**Comment by southsideGLA** [comment]
yes, I'm looking at my Bash book right now to get the syntax for a case statement so I can change that env variable in the middle of a script that will let me fire off updates and tests on every crate sub-dir in my projects/maidsafe directory. Thanks for the reminder about .travis.yml though - I thought that only applied to crust
Funny feeling Im reinventing the wheel here, though....

**Comment by rossmuir** [comment]
OS X and Windows monitored through > http://ci.maidsafe.net:8080/
Linux > https://travis-ci.org/maidsafe/

**Comment by southsideGLA** [comment]
Thanks - I'll check this out

**Comment by benjaminbollen** [comment]
is this resolved, maybe worth re-evaluating after new routing publish (v0.3.0)
