### ISSUE TITLE
relocated id caculated differently

### ISSUE THREAD

**Issue by maqi** [maidsafe/routing#467]
When investigating the issue of failing vault::executable_test on OSX, it is observed some time different nodes will have different close-group view to the network, making the relocated id for a new node different.
i.e. in a network of 3 nodes, for the 4th node, 2 calculated relocating to A, but the other one relocate the 4th to B.
in a most extreme case, I saw among a network of 7, every node having different view and relocate the new node to different ID.
not sure whether this affects the connection establishment.

**Comment by benjaminbollen** [comment]
I will look into this

**Comment by benjaminbollen** [comment]
with group size 8 and quorum of 5 this has an increasingly low probability to occur for a network of 40 nodes or above.  This can be further addressed by redesigning the redirection in address_relocation
