### ISSUE TITLE
interface allowing ClientManager generates more put requests for Backup and Sacrificial copies

### ISSUE THREAD

**Issue by maqi** [maidsafe/routing#468]
when client put an immutable_data, it is supposed that ClientManager(MaidManager) will generate more put requests for Backup and Sacrificial copies.
However, this is un-doable with the current interface.

**Comment by benjaminbollen** [comment]
The interface has been updated to provide -> Vec<MethodCall> for all hanlde calls;

later work will consider a channel based communication, but routing master has this update
