### ISSUE TITLE
Infinite looping CRUST::NewConnection event

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/routing#535]
debug output using routing master (at v0.2.8) and crust (v0.2.1)

Handle find group response
Sending ConnectRequest to peer ae12ce..b47a4d
New CONNECTION; Tcp(V4(127.0.0.1:53078))
CRUST::NewConnection on Tcp(V4(127.0.0.1:53078))
Register unknown connection; Tcp(V4(127.0.0.1:53078))
Send IAM; Tcp(V4(127.0.0.1:53078))
Sending IAM; Tcp(V4(127.0.0.1:53078))
New Message; Tcp(V4(127.0.0.1:53078))
New NON_SIGNED ROUTING MESSAGE; Tcp(V4(127.0.0.1:53078))
Handle I Am
Handle I Am Relocated; Tcp(V4(127.0.0.1:53078))
RT (size : 1) added connected node ae12ce..b47a4d on Tcp(V4(127.0.0.1:53078))
Handle CHURN new node ae12ce..b47a4d
RT: 31465a..e5f0d2
RT: ae12ce..b47a4d
New CONNECTION; Tcp(V4(127.0.0.1:53083))
CRUST::NewConnection on Tcp(V4(127.0.0.1:53083))
Register unknown connection; Tcp(V4(127.0.0.1:53083))
Send IAM; Tcp(V4(127.0.0.1:53083))
Sending IAM; Tcp(V4(127.0.0.1:53083))
New CONNECTION; Tcp(V4(127.0.0.1:53088))
CRUST::NewConnection on Tcp(V4(127.0.0.1:53088))
Register unknown connection; Tcp(V4(127.0.0.1:53088))
Send IAM; Tcp(V4(127.0.0.1:53088))
Sending IAM; Tcp(V4(127.0.0.1:53088))

**Comment by inetic** [comment]
How do I reproduce this?

**Comment by benjaminbollen** [comment]
Should occur any time you start two nodes; but you need to disable the self-validation check on ConnectRequest messages; see commit

https://github.com/maidsafe/routing/commit/b6b30d3ee1d4d869c90169836135b51256b49c96

running the following twice in two different terminals with above change (see commit) and println! at least on Crust::NewConnection, should help you reproduce the bug
cargo run --example simple_key_value_store --release -- --node

**Comment by benjaminbollen** [comment]
What I observe in routing is that after both nodes establish the routing_table connection, no new RoutingMessages are being created or sent;  nonetheless on the bootstrapping side, the node receives an infinite of CRUST::NewConnection events; so somewhere the connection_manager.connect keeps looping.

**Comment by chandraprakash** [comment]
I tried routing node just now on master with https://github.com/maidsafe/routing/commit/b6b30d3ee1d4d869c90169836135b51256b49c96
Can't see the loop happening. Am I missing something ?

Node 1

	prakash@machine:~/rust/maidsafe/routing (master)$ cargo run --example simple_key_value_store  -- --node
	     Running `target/debug/examples/simple_key_value_store --node`
	Crust failed to read config file; Error: Error { repr: Os { code: 2, message: "No such file or directory" } };
	Using default beacon_port 5483 and default bootstraping methods enabled
	crust::Event::NewBootstrapConnection Tcp(V4(127.0.0.1:39583))
	crust::Event::NewBootstrapConnection Tcp(V4(192.168.0.10:39583))
	Got at least one bootstrap connection. Breaking bootstrap loop.
	Received PutPublicId relocated
	                                                          name Some(7aca82..90bda3) from 1e4da9..e0b630
	Enter command (stop)>
	RT: 7aca82..90bda3
	RT: 014085..3c6352



Node 2

    prakash@machine:~/rust/maidsafe/routing (master)$ cargo run --example simple_key_value_store  -- --node
         Running `target/debug/examples/simple_key_value_store --node`
    Crust failed to read config file; Error: Error { repr: Os { code: 2, message: "No such file or directory" } };
    Using default beacon_port 5483 and default bootstraping methods enabled
    crust::Event::NewBootstrapConnection Tcp(V4(127.0.0.1:39583))
    crust::Event::NewBootstrapConnection Tcp(V4(192.168.0.10:39583))
    Got at least one bootstrap connection. Breaking bootstrap loop.
    Received PutPublicId relocated
                                                              name Some(7aca82..90bda3) from 1e4da9..e0b630
    Enter command (stop)>
    RT: 7aca82..90bda3
    RT: 014085..3c6352

**Comment by chandraprakash** [comment]
Tried release version as well. Can't reproduce it.

**Comment by inetic** [comment]
Same here, but trying to see how far the protocol gets

**Comment by dirvine** [comment]
Is it possible you had an old bootstrap.cache file @benjaminbollen  and somehow this caused issues ? I.e. it contained your address and / or 127.0.0.1 and thus did do connects somehow.

**Comment by benjaminbollen** [comment]
I will clear all caches and retry; might be some local error

**Comment by benjaminbollen** [comment]
might be machine dependent, I reproduced it again

INFO:routing::routing_membrane: CRUST::NewConnection on Tcp(V4(127.0.0.1:54314))
DEBUG:routing::routing_membrane: Register unknown connection; Tcp(V4(127.0.0.1:54314))
DEBUG:routing::routing_membrane: Send IAM; Tcp(V4(127.0.0.1:54314))
DEBUG:routing::routing_membrane: Sending IAM; Tcp(V4(127.0.0.1:54314))
INFO:routing::routing_membrane: CRUST::NewConnection on Tcp(V4(127.0.0.1:54315))
DEBUG:routing::routing_membrane: Register unknown connection; Tcp(V4(127.0.0.1:54315))
DEBUG:routing::routing_membrane: Send IAM; Tcp(V4(127.0.0.1:54315))
DEBUG:routing::routing_membrane: Sending IAM; Tcp(V4(127.0.0.1:54315))
INFO:routing::routing_membrane: CRUST::NewConnection on Tcp(V4(127.0.0.1:54316))
DEBUG:routing::routing_membrane: Register unknown connection; Tcp(V4(127.0.0.1:54316))
DEBUG:routing::routing_membrane: Send IAM; Tcp(V4(127.0.0.1:54316))
DEBUG:routing::routing_membrane: Sending IAM; Tcp(V4(127.0.0.1:54316))
INFO:routing::routing_membrane: CRUST::NewConnection on Tcp(V4(127.0.0.1:54317))
DEBUG:routing::routing_membrane: Register unknown connection; Tcp(V4(127.0.0.1:54317))
DEBUG:routing::routing_membrane: Send IAM; Tcp(V4(127.0.0.1:54317))
DEBUG:routing::routing_membrane: Sending IAM; Tcp(V4(127.0.0.1:54317))
INFO:routing::routing_membrane: CRUST::NewConnection on Tcp(V4(127.0.0.1:54318))
DEBUG:routing::routing_membrane: Register unknown connection; Tcp(V4(127.0.0.1:54318))
DEBUG:routing::routing_membrane: Send IAM; Tcp(V4(127.0.0.1:54318))
DEBUG:routing::routing_membrane: Sending IAM; Tcp(V4(127.0.0.1:54318))
INFO:routing::routing_membrane: CRUST::NewConnection on Tcp(V4(127.0.0.1:54319))
DEBUG:routing::routing_membrane: Register unknown connection; Tcp(V4(127.0.0.1:54319))
DEBUG:routing::routing_membrane: Send IAM; Tcp(V4(127.0.0.1:54319))
DEBUG:routing::routing_membrane: Sending IAM; Tcp(V4(127.0.0.1:54319))
INFO:routing::routing_membrane: CRUST::NewConnection on Tcp(V4(127.0.0.1:54320))
DEBUG:routing::routing_membrane: Register unknown connection; Tcp(V4(127.0.0.1:54320))
DEBUG:routing::routing_membrane: Send IAM; Tcp(V4(127.0.0.1:54320))
DEBUG:routing::routing_membrane: Sending IAM; Tcp(V4(127.0.0.1:54320))
INFO:routing::routing_membrane: CRUST::NewConnection on Tcp(V4(127.0.0.1:54321))
DEBUG:routing::routing_membrane: Register unknown connection; Tcp(V4(127.0.0.1:54321))
DEBUG:routing::routing_membrane: Send IAM; Tcp(V4(127.0.0.1:54321))
DEBUG:routing::routing_membrane: Sending IAM; Tcp(V4(127.0.0.1:54321))

**Comment by dirvine** [comment]
Now they all seem to be localhost addresses ?

**Comment by benjaminbollen** [comment]
that's a good observation, I have no saved logs that contain 192.168.x.x though, does not mean it did not occur.  Will pay attention to it being the local loopback

**Comment by benjaminbollen** [comment]
on brians request I ran 

```
bbollen@machine:~/SAFE/rust/crust (master)$ cargo test -- --test test_getifaddr --nocapture
     Running target/debug/crust-35151d3a8f5684b3

running 1 test
   Interface lo has IP 127.0.0.1 netmask 255.0.0.0 broadcast 0.0.0.0
   Interface wlan0 has IP 192.168.0.32 netmask 255.255.255.0 broadcast 192.168.0.255
   Interface docker0 has IP 172.17.42.1 netmask 255.255.0.0 broadcast 172.17.42.1
   Interface lo has IP ::1 netmask ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff broadcast 0.0.0.0
test getifaddrs::test::test_getifaddrs ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured
```

**Comment by benjaminbollen** [comment]
It does always happen on the local loopback address `INFO:routing::routing_membrane: CRUST::NewConnection on Tcp(V4(127.0.0.1:56460))`

I still have it reproduced reliably; (or the nodes don't connect, ie no new connections after the bootstrap connections)

**Comment by dirvine** [comment]
On some architectures if you try and connect to a local ip address, say 192.168.0.3 then the system will make the connection on the 127 address. This is faster as it means the IP stack is not traversed up through the network card etc. and back (hairpinning type route). So we will get connections on 127 for local connections. We should not give them out to others as an address they can connect to us on and instead connect to them still as far as we are concerned on the local ip address (192.xx.x.x. etc.). 

Crust is reporting the actual ip address received on (so can be 127 for local nodes).

**Comment by inetic** [comment]
I don't have an IPv6 interface and I can't reproduce it, perhaps that is it? Could you try to disable it to see if you can still reproduce the problem?

**Comment by benjaminbollen** [comment]
Issue currently paused.
