### ISSUE TITLE
Routing example does not store data in database

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/routing#547]
on latest master of routing v0.2.8
```
INFO:routing::routing_membrane: CRUST::NewConnection on Tcp(V4(127.0.0.1:53514))
ClientManager of 389386..0c81c6 forwarding data to DataManager around 9b71d2..dec043
node didn't have chunk 9b71d2..dec043
```

**Comment by benjaminbollen** [comment]
Forward does not work;

Only the first step is sucessful currently in the example:
<Client::Put | CM::handle_put> - OK
<CM::Put | DM::handle_put> - does not happen

for Get
<Client::Get | DM::Get> - successful but data is missing

**Comment by dirvine** [comment]
There should be no CM, in the example the Location should just be name of chunk not name of self.

**Comment by benjaminbollen** [comment]
I agree, but it is a more useful test of routing if there is at least one network persona transfer;  otherwise a failure like this is not exposed until the vault logic is piled on top of it.

**Comment by benjaminbollen** [comment]
the put_location is very easily corrected and I can run the tests - excepting that I am currently running out of luck and the multiple bootstrap clients are blocking me to connect nodes and test the example

**Comment by benjaminbollen** [comment]
resolved by multiple work in example
