### ISSUE TITLE
Use of unstable features

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/routing#560]
The following feature gates are being used (which disallow this to be built on the Beta or Stable Rust channels):

[`#![feature(convert, core)]`](https://github.com/maidsafe/routing/blob/master/examples/simple_key_value_store.rs#L31)
[`#![feature(convert)]`](https://github.com/maidsafe/routing/blob/master/src/lib.rs#L30)

**Comment by benjaminbollen** [comment]
we use convert in src/error.rs, but that usage is stable now
we don't use core, so that is easily removed,
the remaining unstable use of convert is in NameType::get_full_id() but we never use that; so I can simply remove remove get_full_id, or we can find a better way to append strings

**Comment by benjaminbollen** [comment]
the story is a bit more involved.  I was too quick to think that #[feature(core)] could be dropped from the example (refer to failed #561).

Also removing "get_full_id" from NameType is trivial, as it is unused; but the unit tests for debug_output of the NameType does use the get_full_id to check the correctness of the debug output.

This needs a better was of unit testing the NameType debug output.  Can not be a blocker, but might be a bit more hairy.

**Comment by benjaminbollen** [comment]
almost resolved by latest work in example.  Only the nametype tests use an unstable feature for a secondary was of testing the debug representation if NameType; the test need to be rewritten without the unstable feature
