### ISSUE TITLE
libsodium crash in StructuredData test

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/routing#619]
: sodium_utils3: sodium_utils2: verify1: stream4: stream3: stream2: stream: sodium_version: sodium_utils: sodium_core: sign: shorthash: secretbox_easy2: secretbox_easy: secretbox8: secretbox7: secretbox2: secretbox: scalarmult7: scalarmult6: scalarmult5: scalarmult2: scalarmult: randombytes: pwhash_scrypt_ll: pwhash: onetimeauth7: onetimeauth2: onetimeauth: hash3: hash: generichash3: generichash2: generichash: ed25519_convert: core6: core5: core4: core3: core2: core1: chacha20: box_seed: box_seal: box_easy2: box_easy: box8: box7: box2: box: auth7: auth6: auth5: auth3: auth2: auth: aead_chacha20poly1305

https://travis-ci.org/maidsafe/routing/jobs/76126087

**Comment by benjaminbollen** [comment]
potentially not related to routing, but worth watching out for

**Comment by Fraser999** [comment]
The console output in that link seems to show failed attempts to do `git fetch`.

**Comment by brian-js** [comment]
@benjaminbollen Can we close this issue?
