### ISSUE TITLE
intermittent failure on Authority test

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/routing#625]
---- authority::test::our_authority_full_routing_table stdout ----
	thread 'authority::test::our_authority_full_routing_table' panicked at 'assertion failed: closer_to_target(&nae_or_client_in_our_close_group,
                 &furthest_node_close_group.id, &our_name)', src/authority.rs:246

**Comment by benjaminbollen** [comment]
@ross can you pass me the benchmark script we had from the olden days?

**Comment by ross** [comment]
> @ross can you pass me the benchmark script we had from the olden days?

don't believe i'm the Ross you're looking for :smile:

**Comment by benjaminbollen** [comment]
No :) but you're welcome to hang around !  I meant to call out for @rossmuir

**Comment by rossmuir** [comment]
@benjaminbollen replied in Slack

**Comment by dirvine** [comment]
refactored
