### ISSUE TITLE
Benchmark and compare use of K_COMMON_BITS

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/routing#627]
The bucket index in the routing table is calculated with a static matrix specifying the common bits. Implement a pure calculational restoration of bucket index and write a bench mark test;

If it should be advantageous to preserve the common bits then this pure calculational implementation should become a test to keep evaluating the correctness of the matrix;  this is not a trivial balance to strike in increasing the likelihood for a detecting an off value in the matrix, versus running it on every CI run

**Comment by dirvine** [comment]
I would vote here to rely on the cpu and not a matrix. I feel the same argument can be made for every calculation like this, so hard code log tables etc. To stay correct I would calculate this and as far as we know cpu tech will make it faster anyway as it always does. So to reduce memory usage and stay away from a bit in this being wrong or changed I would calculate it for sure.

**Comment by Fraser999** [comment]
I implemented the matrix in the C++ codebase.  It was significantly faster (I seem to remember several hundreds of times faster) and this function was being called a *lot*.

The test was also reasonable: https://github.com/Fraser999/MaidSafe-Common/blob/next/src/maidsafe/common/tests/identity_test.cc#L230-L247

**Comment by benjaminbollen** [comment]
I would want to redo and implement it as a benchmark test in routing;  If we want to avoid mistakes, we can construct the matrix upon startup of the vault, rather than hard-coding it; and move the hard-coded matrix to a unit test that validates it is calculated correctly on start up ?

**Comment by dirvine** [comment]
I just see all kinds of hurt here, a cpu does just that for us. If this is a huge saving in speed then OK but what cost, memory ? etc. I see this as something we would need to consider much more, how well does it perform on different machines / platforms, how would it affect exe size, mem use etc as well as how do we know nobody tinkered with it and if they did would we be able to debug it easily.

**Comment by benjaminbollen** [comment]
true, the benchmark would not take memory into account, but memory cost should be static at 64 kB.

**Comment by dirvine** [comment]
re-factored
