### ISSUE TITLE
duplicated requests are not get filtered out

### ISSUE THREAD

**Issue by maqi** [maidsafe/routing#632]
for each put request from client, each PM receiving 4 put requests, and each PN receiving 4 put requests as well, indicates the accumulator in routing doesn't work as expected.
this is observed using the test in the vault PR https://github.com/maidsafe/safe_vault/pull/201

**Comment by brian-js** [comment]
Investigate also the effect of filtering messages sent by a node before the message is sent.

**Comment by benjaminbollen** [comment]
I think I see the question: the PM NodeManagers get the request from the DM, a group.  The routing example currenlty does not have this case - it was taken out - (CM to DM).

This will help where to find the bug !

**Comment by benjaminbollen** [comment]
@brian will make (a modified copy of) the example that use Put <Client | ClientManagers> <ClientManagers| DataManagers> to better illustrate and debug this problem from routing

**Comment by maqi** [comment]
Seems this has been resolved with some updates in routing.
The duplicated requests are not observed anymore.
