### ISSUE TITLE
Cargo build fails on Xubuntu 14.04 32-bit machine

### ISSUE THREAD

**Issue by mabeebam** [maidsafe/routing#659]
rustc --version
rustc 1.4.0-nightly (d50352419 2015-08-29)

"cargo build" fails with the following error when building:
src/filter.rs:26:5: 26:69 error: the trait `core::cmp::PartialOrd` is not implemented for the type `sodiumoxide::crypto::sign::ed25519::Signature` [E0277]
src/filter.rs:26     claimant_filter: ::message_filter::MessageFilter<ClaimantFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/filter.rs:26:5: 26:69 help: run `rustc --explain E0277` to see a detailed explanation
src/filter.rs:26:5: 26:69 note: required by `message_filter::MessageFilter`
src/filter.rs:26     claimant_filter: ::message_filter::MessageFilter<ClaimantFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/filter.rs:26:5: 26:69 error: the trait `core::cmp::Ord` is not implemented for the type `sodiumoxide::crypto::sign::ed25519::Signature` [E0277]
src/filter.rs:26     claimant_filter: ::message_filter::MessageFilter<ClaimantFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/filter.rs:26:5: 26:69 help: run `rustc --explain E0277` to see a detailed explanation
src/filter.rs:26:5: 26:69 note: required by `message_filter::MessageFilter`
src/filter.rs:26     claimant_filter: ::message_filter::MessageFilter<ClaimantFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/filter.rs:26:5: 26:69 error: the trait `core::hash::Hash` is not implemented for the type `sodiumoxide::crypto::sign::ed25519::Signature` [E0277]
src/filter.rs:26     claimant_filter: ::message_filter::MessageFilter<ClaimantFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/filter.rs:26:5: 26:69 help: run `rustc --explain E0277` to see a detailed explanation
src/filter.rs:26:5: 26:69 note: required by `message_filter::MessageFilter`
src/filter.rs:26     claimant_filter: ::message_filter::MessageFilter<ClaimantFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/filter.rs:27:5: 27:74 error: the trait `core::cmp::PartialOrd` is not implemented for the type `sodiumoxide::crypto::hash::sha256::Digest` [E0277]
src/filter.rs:27     message_filter: ::message_filter::MessageFilter<RoutingMessageFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/filter.rs:27:5: 27:74 help: run `rustc --explain E0277` to see a detailed explanation
src/filter.rs:27:5: 27:74 note: required by `message_filter::MessageFilter`
src/filter.rs:27     message_filter: ::message_filter::MessageFilter<RoutingMessageFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/filter.rs:27:5: 27:74 error: the trait `core::cmp::Ord` is not implemented for the type `sodiumoxide::crypto::hash::sha256::Digest` [E0277]
src/filter.rs:27     message_filter: ::message_filter::MessageFilter<RoutingMessageFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/filter.rs:27:5: 27:74 help: run `rustc --explain E0277` to see a detailed explanation
src/filter.rs:27:5: 27:74 note: required by `message_filter::MessageFilter`
src/filter.rs:27     message_filter: ::message_filter::MessageFilter<RoutingMessageFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/filter.rs:27:5: 27:74 error: the trait `core::hash::Hash` is not implemented for the type `sodiumoxide::crypto::hash::sha256::Digest` [E0277]
src/filter.rs:27     message_filter: ::message_filter::MessageFilter<RoutingMessageFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/filter.rs:27:5: 27:74 help: run `rustc --explain E0277` to see a detailed explanation
src/filter.rs:27:5: 27:74 note: required by `message_filter::MessageFilter`
src/filter.rs:27     message_filter: ::message_filter::MessageFilter<RoutingMessageFilter>,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 6 previous errors
Could not compile `routing`.

**Comment by dirvine** [comment]
Just to check, but can you try `cargo update` as it looks like an older version of sodiumoxide may be in your build folder perhaps?

**Comment by mabeebam** [comment]
Hi David, thank you solved my issue.

**Comment by dirvine** [comment]
You're welcome, thanks for testing.
