### ISSUE TITLE
Expose `NameType`'s length and/or expose `NameType::generate_random()`

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/routing#674]
It would be useful if Routing either exposed [`NAME_TYPE_LEN`](https://github.com/maidsafe/routing/blob/master/src/name_type.rs#L24) or provided a static getter in the `NameType` struct, e.g.

    pub fn len() -> usize { NAME_TYPE_LEN }

The only alternatives I think we currently have now are to use the `len()` of an actual instance, or just use a hard-coded value of `64`, neither of which is ideal.

The need arises in my case because I'm creating a random `NameType`for testing Vault accounts.  I have to go through the horribly-convoluted process of:

    ::routing::NameType(::routing::types::vector_as_u8_64_array(
        ::routing::types::generate_random_vec_u8(64)))

(well - obviously I don't *have* to - I could write my own functions for this, but in the interests of DRY...)

I would much rather just use:

    ::routing::NameType::generate_random()

but this hasn't been exposed and I seem to remember that was by design.  So failing this becoming available, I'd rather not hard-code `64` - i.e. I'd rather write:

    ::routing::NameType(::routing::types::vector_as_u8_64_array(
        ::routing::types::generate_random_vec_u8(::routing::NameType::len())))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^

Even this doesn't shield us from Routing changing from 64, since I imagine the public function `vector_as_u8_64_array` would get renamed.

**Comment by benjaminbollen** [comment]
I would argue that it's better to expose ::generate_random() - but of course Im not objecting to the ::len() getter.  I believe the design was for it to be exposed under #[cfg(test)] which would still be the case
