### ISSUE TITLE
ResponseError::description() for HadToClearSacrificial: "\n" really intended in line 58 of error.rs?

### ISSUE THREAD

**Issue by mabeebam** [maidsafe/routing#694]
Hi,

one more small thing: is newline within error description of line 58 in error.rs really intended?
Please consider also the test assert at line 360-364, that currently succeeds with "\n"

Cheers!

**Comment by Fraser999** [comment]
Doubt it - it looks like it's missing a `/` to continue the line.  Good spot!

**Comment by benjaminbollen** [comment]
I agree, that's a formatting error sneaked in :).  Do you want to resolve this one @mabeebam?  If so you can assign it to yourself.  Otherwise we'll pick it up

**Comment by mabeebam** [comment]
@benjaminbollen no prob, i will do it.
