### ISSUE TITLE
code deduplication in examples and integration tests

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/routing#697]
the latest example code for testing churn and refresh messages with a client account is in examples/key_value_store.rs;  this code needs to be 
1. ported to /test_utils/node.rs
2. both examples need to use /test_utils/node.rs; initially simple_key_value_store can be left untouched as a "simple" example directly demonstrating the minimal use-case.  But key_value_store needs to use the same code as the integration tests to ensure that no errors are induced because of out-of-sync duplicated code

**Comment by benjaminbollen** [comment]
point 1 addressed by @brian-js in MAID-1348

**Comment by dirvine** [comment]
Now re-factored
