### ISSUE TITLE
Upper limit of size of StructuredData unclear and unenforced

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/routing#720]
The max size of a single instance of `StructuredData` is specified as [`MAX_STRUCTURED_DATA_SIZE_IN_BYTES`](https://github.com/maidsafe/routing/blob/e68ccf621d0f3693a81daaf534271af97d4fda15/src/structured_data.rs#L18-L19) with the comment:

> Maximum allowed size for a Structured Data to grow to

It isn't clear what this means - is this the size in memory of an instance, the size of the `data` field only, or the size after encoding via the rustc-serialize `encode` function?

Also, it would be good if Routing enforced this limit.

**Comment by canndrew** [comment]
Looks like it's [used in safe_client](https://github.com/maidsafe/safe_client/blob/master/src/structured_data_operations/mod.rs#L59) as the size after encoding.
