### ISSUE TITLE
Lot of DEBUG:routing::routing_node: message from unknown connection

### ISSUE THREAD

**Issue by Ghaunt** [maidsafe/routing#722]
I get a lot of that and when I look at the code https://github.com/maidsafe/routing/blob/master/src/routing_node.rs#L155-L161 nothing is done with it.

Found this: https://github.com/maidsafe/routing/blob/master/src/routing_node.rs#L309-L314 I wonder why he still send the message if it is still unidentified.

**Comment by benjaminbollen** [comment]
We do need to clean up routing debug statements.  But the first statements you mention are quite valuable, as with crust 0.2 routing never* saw this case hit.  And with the new crust (since v0.3) we hit it quite a lot.  Other problems with the connections occur as well, and work is being put into a full review of the routing connection management in relation to the new crust.  It will in fact be the focus point for routing in Rust-5 sprint.

*observed

**Comment by benjaminbollen** [comment]
On your second point: on the first "hello" we don't know who the counterparty is, so both sides send a "hello".  Upon reception of the hello, the alpha-rule decides which side will confirm the connection; hence this logic which was induced by the symmetric nature of new connections in crust 0.2

with the new crust 0.3 and later, we have explcit "on_accept" and "on_connect" as one part of our role in the connection establishment.  This is being detailed in the Connection Management RFC (continued tomorrow) and again, in Rust-5 with the Connection Management refactoring this concept of alpha will disappear.

**Comment by benjaminbollen** [comment]
Re-opened, as the messages to an unknown connection is an active bug.  Although addressed in Rust-5, best to keep the issue open.

**Comment by Ghaunt** [comment]
>
DEBUG:routing::routing_node: Hello, it is Node(2f7db8..fa9732) on Connection(Tcp V4(192.168.0.101:46808) -> V4(192.168.0.101:41368))
DEBUG:routing::routing_node: We are not alpha and the hello was not confirmed yet, awaiting alpha.
DEBUG:routing::routing_node: Hello, it is Node(2f7db8..fa9732) on Connection(Tcp V4(192.168.0.101:46808) -> V4(192.168.0.101:41368))
DEBUG:routing::routing_node: This hello message successfully confirmed our address, Node(96837b..f87e91)
DEBUG:routing::routing_node: Drop relay Unidentified(Connection(Tcp V4(192.168.0.101:46808) -> V4(192.168.0.101:41368)), false) connection in favour of Routing(2f7db8..fa9732)
DEBUG:routing::routing_node: Core refused Node(2f7db8..fa9732) on Connection(Tcp V4(192.168.0.101:46808) -> V4(192.168.0.101:41368)) and dropped the connection
>

The node accept an address with a name that is tied to the IP instead of the name from the hello message.
Message farther than one hop can't be made. Node only accept name from direct address wrongly.

I found too that when a Node is dropped it drop the direct connection. I don't know why they are tied together which should be wrong. Connection made be crust should only be dropped from routin if it misbehave from it. And if crust decide to disconnect a direct connection, routing should not be aware of that.

**Comment by Ghaunt** [comment]
My last comment is false. Here is an update.
I tweaked a little the output to have a better understanding on this specifique issue.

Vault 1
>
INFO:routing::routing_node: RoutingNode Client(15db83..5f30e8) listens on [Tcp(V4(192.168.0.101:5483))]
INFO:routing::routing_core: RT(1) added Peer(identity: Routing(e4bda8..dea4e9), connection: Connection(Tcp V4(192.168.0.101:34070) -> V4(192.168.0.101:37251)))
INFO:routing::routing_core: RT(2) added Peer(identity: Routing(5ed5fd..7a62e2), connection: Connection(Tcp V4(192.168.0.101:47212) -> V4(192.168.0.101:33309)))
>

Vault 2
>
INFO:routing::routing_node: RoutingNode Client(ca2aa5..fafe4b) listens on [Tcp(V4(192.168.0.101:37251))]
INFO:routing::routing_node: Assigned network name e4bda8..dea4e9 and our address now is Node(e4bda8..dea4e9)
INFO:routing::routing_core: RT(1) added Peer(identity: Routing(17fb8a..045677), connection: Connection(Tcp V4(192.168.0.101:37251) -> V4(192.168.0.101:34070)))
INFO:routing::routing_core: RT(2) added Peer(identity: Routing(5ed5fd..7a62e2), connection: Connection(Tcp V4(192.168.0.101:47210) -> V4(192.168.0.101:33309)))
>

Vault 3
>
INFO:routing::routing_node: RoutingNode Client(40f088..942b8e) listens on [Tcp(V4(192.168.0.101:33309))]
INFO:routing::routing_node: Assigned network name 5ed5fd..7a62e2 and our address now is Node(5ed5fd..7a62e2)
INFO:routing::routing_core: RT(1) added Peer(identity: Routing(17fb8a..045677), connection: Connection(Tcp V4(192.168.0.101:34884) -> V4(192.168.0.101:5483)))
INFO:routing::routing_core: RT(2) added Peer(identity: Routing(e4bda8..dea4e9), connection: Connection(Tcp V4(192.168.0.101:33309) -> V4(192.168.0.101:47210)))
INFO:routing::routing_node: message from unknown connection Connection(Tcp V4(192.168.0.101:33309) -> V4(192.168.0.101:47212))
INFO:routing::routing_node: message from unknown connection Connection(Tcp V4(192.168.0.101:33309) -> V4(192.168.0.101:47212))
INFO:routing::routing_node: message from unknown connection Connection(Tcp V4(192.168.0.101:33309) -> V4(192.168.0.101:47212))
>

V1 > V2: V4(192.168.0.101:34070) -> V4(192.168.0.101:37251)
V2 > V1: V4(192.168.0.101:37251) -> V4(192.168.0.101:34070)
Good! Same ports.

V2 > V3: V4(192.168.0.101:47210) -> V4(192.168.0.101:33309)
V3 > V2: V4(192.168.0.101:33309) -> V4(192.168.0.101:47210)
Good! Same ports.

V1 > V3: V4(192.168.0.101:47212) -> V4(192.168.0.101:33309)
V3 > V1: V4(192.168.0.101:34884) -> V4(192.168.0.101:5483
Bad! Different ports. Message from unknown connection begin because of that.

**Comment by dirvine** [comment]
This has been re-factored now and much cleaner.
