### ISSUE TITLE
NameType is a misleading, unconventional name.

### ISSUE THREAD

**Issue by canndrew** [maidsafe/routing#723]
To me, the name `NameType` suggests a type that specifies what type of name we're dealing with, similar to how `ImmutableDataType` specifies what type of immutable data we're dealing with (eg. `Normal`, `Backup` or `Sacrificial`). But actually `NameType` is meant to be read as "the type of names". Here, the -`Type` suffix is redundant - we already know that it's a type. It also doesn't follow the normal rust naming conventions - ie. we don't call `String` `StringType`, `Vec` `VecType` or `ImmutableDataType` `ImmutableDataTypeType`.

`NameType` should be renamed to just `Name` or something more descriptive.

**Comment by Fraser999** [comment]
I couldn't agree more.

I don't think there's much we can do beyond `Name` though.  This is used to identify data on the network, nodes on the network and empty elements in the address space.  Different, but equally non-descriptive alternatives include `Address` or `Id`.

I think we could make better use of the type system though to avoid runtime errors; e.g. having a policy to generally avoid using bare `Name`s outside of Routing, rather wrapping them in context-specific structs so they can't be easily (accidentally) interchanged.

**Comment by benjaminbollen** [comment]
I agree too :), but we have an internal history of having settling on a single type.  So internally we are mostly happy we have a single type for it.  But you are right on the renaming request.

**Comment by canndrew** [comment]
What should they be called then? Maybe `XorAddr`?

> we have an internal history of having settled on a single type. So internally we are mostly happy we have a single type for it.

What's the advantage of a single type though? I envision these wrappers would be very simple. Something like:

    struct NodeAddr {pub xor: XorAddr}
    struct DataAddr {pub xor: XorAddr}

These would make code more readable: whether a function takes a `NodeAddr` or a `DataAddr` tells you a lot more about it compared to if it just takes a `XorAddr`. And (as @Fraser999 points out) it makes code less buggy: it guarantees you'll never use the address of a piece of data as the address of a node.

**Comment by dirvine** [comment]
This is now an XorName and moved into its own crate
