### ISSUE TITLE
Looping for event it's not a solution!

### ISSUE THREAD

**Issue by Ghaunt** [maidsafe/routing#725]
https://github.com/maidsafe/routing/blob/master/src/routing_node.rs#L198

I speak for myself here, but I seriously would not accept that if I was the leader. I know now the nature of rust and how it work. I would suggest a way to optimize it and or implement it. It should not be too complicated. A solution I have in mind is having a library (a crate) that handle messaging like the Windows Messages: https://msdn.microsoft.com/en-us/library/windows/desktop/ms632590(v=vs.85).aspx

I saw the TcpStream too. There is no Async method. That one should be implemented too in another version. Ex.: This new implementation can use the Messaging to give an event back.

Conclusion:
I don't know if it exist but I would recommend, a Messaging like the Windows one, a Timer Event and messaging across all the library (crate).  A Task Queue or Job Queue (with default one thread for each core), for all this threads.

Well having a good sync with everything it should be good.

I put this issue here but it's just there is no place for a global issue. Well I'm still newbie with git.

Well the title may not be appropriate. The one I suggest is still looping but with a halt kind so it does not waste CPU resource like using Channel.

CORRECTION: Meaning TcpStream not TcpConnection

**Comment by Ghaunt** [comment]
I found this:
https://github.com/carllerche/mio

Already mentionned in crust but that should help in all of your repository.

**Comment by dirvine** [comment]
Yes some rust core devs are working on MIO for Windows, it will make a big difference

**Comment by canndrew** [comment]
The solution here is to use the `select!` macro.

**Comment by ustulation** [comment]
Select is unstable. I've handled this by constructing a mechanism for it - `EventSender`. Have a look here in [maidasfe_launcher](https://github.com/maidsafe/safe_launcher/blob/master/src/event_sender.rs) - The code [here](https://github.com/maidsafe/safe_launcher/blob/master/src/launcher/ipc_server/mod.rs) has to listen to events from large number of varied groups for achieving event-subsetting, the purpose of which I've explained in [this task](https://maidsafe.atlassian.net/browse/MAID-1405) in one of the comments there, and it does all that in a single thread without any spin-lock and in a single thread.

**Comment by dirvine** [comment]
Replaced with better pattern from maidafe_utillities
