### ISSUE TITLE
Non-clonable errors

### ISSUE THREAD

**Issue by ustulation** [maidsafe/routing#739]
Routing errors are non-clonable which makes all errors composing them to be non-clonable as well which restricts coding style. As can be seen errors are non-clonable because composing some form of std::io::Error. std::io::Error not being clonable is an issue discussed online and also raised it in rust meeting i had attended with the core guys. It's a low priority task for them. In the mean-while could we **not** compose `std::io::Error` and just compose the debug string they produce so everything's clonable ? Nobody right now seems to care about an absolute fine grained control over io::Errors anyway. So say we could have:
https://github.com/maidsafe/routing/blob/master/src/error.rs#L166

as:

```
Io(String),
```

and fill it as

```
let debug_str = format!("{:?}", actual_io_error);
... RoutingError::Io(debug_str) ...
```

Similarly for cbor errors because cbor error uses io::error internally i think, hence not clonable.

Would this be objectionable ?

**Comment by Fraser999** [comment]
We're losing a lot of type-safety then aren't we?  If we were to do this, I think Routing should at least do something like provide helper functions rather than relying on users to pass the "right sort of string" into the different variants of the `RoutingError`.  I have to say that this feels like a backwards step, but I'm not sure about the best way forward.

**Comment by ustulation** [comment]
>  rather than relying on users to pass

Ah ok .. You mean RoutingError and other Error types in routing are generated by crates other than routing too ? I didn't know that.

> We're losing a lot of type-safety then aren't we?

Just like if a user can put anything into a string a use can _invent_ an io error and put it there -e.g. straight from the rust-api docs:
```
let custom_error = Error::new(ErrorKind::Other, "oh no!");
```

Also i am not aware of anyone checking a particular sub-detail of an error and acting on it so far. Just asking - is anyone actually doing this, esp for Io::Error ?

**Comment by dirvine** [comment]
>Also i am not aware of anyone checking a particular sub-detail of an error and acting on it so far. Just asking - is anyone actually doing this, esp for Io::Error ?
Good point, but I feel we should and will be paying much more attention to errors soon. We actually swallow some etc. but will need to act properly on them (i.e. why we cannot write a file etc.). I would perhaps recommend we maintain the ability to do that in the near future if that makes sense.

**Comment by canndrew** [comment]
`clone` also gets over-used a bit in some of the code I've seen. It's better to use borrowing where possible.

**Comment by madadam** [comment]
We've been doing just fine all this time without clonable errors, so closing this.
