### ISSUE TITLE
Groups on a small network are not necessarily GroupSize by observation with Rust-3 (legacy)

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/routing#746]
On the version of routing 0.3 and crust 0.2 it is observed that groupsizes are not necessarilly 8 as expected.  They are deterministic and stable in their membership however.  It is argued that this is caused by a sparse population of the address space, and the potential inaccuracy of crust 0.2 to report broken connections, or failure of sending messages; which could have at a high likelihood fragmented or partially fragmented the groups, cutting out part of the actual group.

This issue is raised to track the observation on the renewed routing 0.4 and crust 0.4 after completion of Rust-5

**Comment by afck** [comment]
This has been fixed with the implementation of [RFC 19](https://github.com/maidsafe/rfcs/blob/master/text/0019-new-kademlia-routing-logic/0019-new-kademlia-routing-logic.md).
