### ISSUE TITLE
Switch the semantics of Post and Put

### ISSUE THREAD

**Issue by madadam** [maidsafe/routing#875]
Post should be for creating new objects and Put for updating existing ones, like in REST. Routing currently has these meanings reversed.

**Comment by dirvine** [comment]
Well kinda, Post in rest is Add or update and Put is add only AFAIK. So we do not really reverse these, just we restrict Post to update only. Agree it needs discussion though.

**Comment by madadam** [comment]
I think you are confusing POST and PUT in REST. In REST, POST is used to create a new resource where the server gives you back the ID (URL) of the resource. PUT is used to update a resource with already existing ID (URL). PUT can be used also to create a new resource if it makes sense to supply its id to the server (as opposed to have it generated by the server). This stackoverflow question seems to explain it well: http://stackoverflow.com/questions/630453/put-vs-post-in-rest

Note this is how it works in REST, I'm not yet sure how well this translates to routing. For example, are XorNames our equivalent of URLs?

**Comment by dirvine** [comment]
Ah yes I see your point @madadam. Nice one. In our case an XOR address can be considered a url

**Comment by Thierry61** [comment]
When I read the same link (http://stackoverflow.com/questions/630453/put-vs-post-in-rest) I come to a different conclusion:

- Post is adding a new subordinate to an existing resource
- Put is creating or replacing a resource.

So I think the semantics of Post and Put are currently correct in Maidsafe crates and shouldn't be switched.

**Comment by afck** [comment]
We will stick to the current semantics of Post and Put for now.
