### ISSUE TITLE
Consider alternative designs for `ImmutableData`.

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/routing#947]
There are two possible alternative designs for `ImmutableData` which have been discussed on Slack and implemented in my fork of Routing.

This issue is a placeholder to remind us of these alternatives and revisit them at a future point.

The first approach makes the `ImmutableDataName` an enum to replace the type tag currently used: https://github.com/Fraser999/routing/tree/mutation_of_immutable_data.

The second approach makes the `ImmutableData` itself an enum and defines three new name types to allow differentiating when making a Get request: https://github.com/Fraser999/routing/tree/another_mutation_of_immutable_data.

**Comment by afck** [comment]
Closing this, as we removed the backup and sacrificial immutable data types.
